import { IrnogEvent } from "../types";

export const Irnog2: IrnogEvent = {
  title: "دومین",
  time: "دوشنبه - 26 آذرماه 1397",
  location: {
    country: "ایران",
    city: "تهران",
    detail: "مرکز همایش های بین المللی رایزن",
    locationLink:
      "https://www.google.com/maps/dir//Rayzan+International+Conference+Centre+Tehran+Province,+Tajrish+Unnamed+Road+RF8J%2BMR4/@35.8166345,51.4820754,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3f8e1acef7932ab3:0xa96dea0f6e2efda6!2m2!1d51.4820754!2d35.8166345?entry=ttu&g_ep=EgoyMDI1MDMwOC4wIKXMDSoASAFQAw%3D%3D",
  },
  irnogAgenda: [
    {
      presenter: "شاهین غرقی",
      presentationTitle: "افتتاحیه",
      presentationLink: "https://www.aparat.com/v/f76gj5s",
    },
    {
      presenter: "Vahan Hovsepyan",
      presentationTitle: "RIPE NCC Update",
      presentationLink: "https://www.aparat.com/v/a89vz",
    },
    {
      presenter: "علیرضا وزیری",
      presentationTitle: "روش‌های کنترل سوء استفاده رایانه‌ای",
      presentationLink: "https://www.aparat.com/v/u55bzat ",
    },
    {
      presenter: "میلاد افشاری",
      presentationTitle: "RIPE Atlas statistics in Iran and the world",
      presentationLink: "https://www.aparat.com/v/NqFQL",
    },
    {
      presenter: "پوریا موسوی‌زاده",
      presentationTitle: "Decentralizing Internet Infrastructure",
      presentationLink: "https://www.aparat.com/v/q0D8K",
    },
    {
      presenter: "احسان قاضی‌زاده",
      presentationTitle: "BGPSEC",
      presentationLink: "https://www.aparat.com/v/q1R9G",
    },
    {
      presenter: "محمد خطیبی",
      presentationTitle: "The Iranian NOG",
      presentationLink: "https://www.aparat.com/v/j517p8l",
    },
    {
      presenter: "امید کوثری",
      presentationTitle: "Cache, the Good, the Bad and the Ugly",
      presentationLink: "https://www.aparat.com/v/r477r40",
    },
    {
      presenter: "کاظم فلاحی",
      presentationTitle: "حمله DNS",
      presentationLink: "https://www.aparat.com/v/f227oor",
    },
    {
      presenter: "میلاد افشاری",
      presentationTitle: "اختتامیه",
      presentationLink: "https://www.aparat.com/v/bjg32",
    },
  ],
  sponsers: {
    platinumSponsors: [
      {
        logo: "/logo/sponsers/irnog2/ncc.png",
        link: "https://www.ripe.net/",
        name: "RIPE NCC",
      },
      {
        logo: "/logo/sponsers/irnog2/world communications development.jpg",
        link: "#",
        name: "world communications development",
      },
    ],
    moralSponsor: [
      {
        logo: "/logo/sponsers/irnog2/webcheen.png",
        link: "http://www.webcheen.com/",
        name: "webCheen",
      },
    ],
  },
  Participants: [
    { firstname: "میلاد", lastname: "افشاری", company: "آسیاتک" },
    { firstname: "امید", lastname: "کوثری", company: "شبکه ارتباط شبدیز" },
    { firstname: "شاهین", lastname: "غرقی", company: "آسیاتک" },
    { firstname: "شهاب", lastname: "وهاب زاده", company: "آسیاتک" },
    { firstname: "علیرضا", lastname: "کریمی", company: "سپنتا" },
    {
      firstname: "علیرضا",
      lastname: "غلام شاهی",
      company: "ارتباطات شبکه علمی ایران",
    },
    { firstname: "جعفر", lastname: "بخشی فر", company: "آسیاتک" },
    { firstname: "فریبا", lastname: "اوصالی", company: "سپنتا" },
    {
      firstname: "علیرضا",
      lastname: "باوی",
      company: "ارتباطات ثابت اوا اروند",
    },
    { firstname: "پویا", lastname: "خوشخو", company: "گسترش ارتباطات سپنتا" },
    { firstname: "سعیده", lastname: "مجیدی", company: "Ito" },
    {
      firstname: "مریم",
      lastname: "آقامحمد",
      company: "انتقال داده های آسیاتک",
    },
    { firstname: "رضا", lastname: "طحان لتیباری", company: "همراه اول" },
    { firstname: "الهه", lastname: "آجرلو", company: "آسياتك" },
    { firstname: "تارا", lastname: "بجنوردی", company: "آسیاتک" },
    { firstname: "علیرضا", lastname: "احمدی", company: "ماهان نت" },
    {
      firstname: "محبوبه",
      lastname: "چنگیزی محمدی",
      company: "سازمان فناوری اطلاعات ایران",
    },
    {
      firstname: "علی اکبر",
      lastname: "اخوان آریج",
      company: "داده پردازی فناوا",
    },
    { firstname: "پدرام", lastname: "قفقازی", company: "مبنا تلکام" },
    { firstname: "پیمان", lastname: "یگانه", company: "آسیاتک" },
    { firstname: "علیرضا", lastname: "محقق", company: "ارتباطات زیرساخت" },
    { firstname: "مجتبی", lastname: "منیعی", company: "تک نت" },
    { firstname: "میثم", lastname: "مجیدی", company: "سازمان فناوری اطلاعات" },
    { firstname: "امین", lastname: "ملک قاسمی", company: "آترین" },
    {
      firstname: "روژیا",
      lastname: "خوردبین",
      company: "شرکت ارتباطات زیر ساخت",
    },
    { firstname: "رضا", lastname: "بهروزی", company: "آسیاتک" },
    {
      firstname: "لیلا",
      lastname: "آقایی میبدی",
      company: "شرکت ارتباطات زیرساخت",
    },
    {
      firstname: "بهروز",
      lastname: "عباس زاده",
      company: "سازمان فناوری اطلاعات ایران",
    },
    { firstname: "محمد حسین", lastname: "محسنی", company: "" },
    { firstname: "بهشاد", lastname: "رضایی", company: "تک نت" },
    { firstname: "وحید", lastname: "خوشنود", company: "تک نت" },
    { firstname: "محمد", lastname: "بياتي", company: "حسابگرپردازغرب(تك نت)" },
    { firstname: "حمیدرضا", lastname: "باقری", company: "آسیاتک" },
    {
      firstname: "محسن",
      lastname: "مهدی پور",
      company: "انتقال داده های اسیاتک",
    },
    { firstname: "مهدی", lastname: "تقی‌زاده", company: "ihome.ir" },
    { firstname: "محمد حسن", lastname: "هاشمی", company: "مارال هاست" },
    { firstname: "سید کیارش", lastname: "گلستانه", company: "مارال هاست" },
    { firstname: "محمود", lastname: "سیدرضویان", company: "پیشگامان" },
    { firstname: "علیرضا", lastname: "نوروزی صفا", company: "لایزر" },
    { firstname: "دانش", lastname: "زینالی", company: "Rightel" },
    { firstname: "فرشاد", lastname: "منتخبی", company: "افرانت" },
    { firstname: "zohreh", lastname: "chizari", company: "irost" },
    {
      firstname: "سید پوریا",
      lastname: "موسوی زاده تهرانی",
      company: "آسیاتک",
    },
    { firstname: "علی", lastname: "داوری", company: "شبکه گستر درنا" },
    { firstname: "کیوان", lastname: "قدیمی", company: "" },
    { firstname: "مسعمود", lastname: "رنجبر", company: "" },
    { firstname: "پژمان", lastname: "رابطی", company: "شبکه ارتباط شبدیز" },
    {
      firstname: "احسان",
      lastname: "گورابی",
      company: "پژوهشگاه ارتباطات و فناوری اطلاعات",
    },
    { firstname: "رضا", lastname: "محمودی", company: "دورتک" },
    { firstname: "یونس", lastname: "دریس", company: "ارتباطات هوشمند گندم" },
    { firstname: "علی", lastname: "حجار", company: "ِاپلیمان" },
    { firstname: "امیر عباس", lastname: "زارع شحنه", company: "همراه اول" },
    { firstname: "نیما", lastname: "کثیری نیا", company: "" },
    { firstname: "ریحانه", lastname: "جاویدی", company: "شرکت مخابرات ایران" },
    { firstname: "علی", lastname: "نیکنام", company: "تیم پردیس" },
    { firstname: "نیما", lastname: "بخار", company: "AVAKATAN" },
    { firstname: "محمدتقی", lastname: "مظفری", company: "گرین وب" },
    { firstname: "Ehsan", lastname: "Javidi", company: "Greenweb" },
    { firstname: "ابراهیم", lastname: "خردمند", company: "AVAKATAN" },
    { firstname: "فرید", lastname: "محمودی", company: "AVAKATAN" },
    {
      firstname: "میترا",
      lastname: "باغشاهی",
      company: "انتقال داده های آسیاتک",
    },
    { firstname: "سعید", lastname: "ثائبی", company: "گرین وب" },
    { firstname: "سوگند", lastname: "قربانی", company: "آسیاتک" },
    {
      firstname: "سپیده",
      lastname: "احمدی",
      company: "شرکت انتقال داده های آسیاتک",
    },
    { firstname: "اميرحسين", lastname: "ثابت", company: "صفرويك" },
    { firstname: "اشکان", lastname: "کیانی", company: "پیوندآزادشبکه" },
    {
      firstname: "ماهرخ",
      lastname: "نعمت اللهی",
      company: "پارسان لین ارتباطات",
    },
    { firstname: "الهام", lastname: "فهمیده", company: "آسیاتک" },
    { firstname: "محمد رسول", lastname: "اکبری", company: "" },
    { firstname: "محمدرضا", lastname: "حسینی", company: "" },
    { firstname: "مرتضی", lastname: "ابراهیم زاده", company: "پارس آنلاین" },
    { firstname: "رضا", lastname: "زند", company: "فناپ تلکام" },
    { firstname: "ابراهیم", lastname: "مجتبایی", company: "رسپینا" },
    { firstname: "احسان", lastname: "قاضی‌زاده", company: "فناپ‌تلکام" },
    {
      firstname: "سید مهدی",
      lastname: "وجدانی زاده",
      company: "ارتباطات زیرساخت",
    },
    { firstname: "امیر", lastname: "اثناعشری", company: "ASD Group" },
    { firstname: "هادی", lastname: "پاشازاده", company: "پارس آنلاین" },
    {
      firstname: "احمد",
      lastname: "نویدی",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "Arash", lastname: "Nasiri", company: "گروه ابر توسعه دريا" },
    {
      firstname: "مجتبی",
      lastname: "امانی",
      company: "شرکت فناوران اطلاعات و ارتباطات آترین",
    },
    { firstname: "علیرضا", lastname: "کولیوند", company: "پیشگامان" },
    { firstname: "سید علی", lastname: "صالح ایمن", company: "نگاه روشن پارس" },
    { firstname: "علاءالدین", lastname: "محبی آشتیانی", company: "نوکیا" },
    { firstname: "طاهره", lastname: "توانا", company: "هواوی" },
    {
      firstname: "میثم",
      lastname: "رحمتیان",
      company: "شرکت راهکار داده پرداز",
    },
    {
      firstname: "شهروز",
      lastname: "شکوه زنگنه",
      company: "گسترش ارتباطات مبنا",
    },

    { firstname: "علی", lastname: "نوروزی", company: "پارس آنلاین" },
    { firstname: "محمد", lastname: "صاحبدل", company: "هاست ایران" },
    { firstname: "فرهاد", lastname: "فولادی", company: "خدمات انفورماتیک" },
    { firstname: "صالح", lastname: "میران", company: "" },
    { firstname: "حامد", lastname: "کارگرزاده", company: "" },
    { firstname: "محمد رضا", lastname: "مستمع", company: "راسپینا نت پارس" },
    { firstname: "اندیشه", lastname: "داداش زاده", company: "رهیارسرور" },
    { firstname: "علی", lastname: "پرتوی", company: "افرانت" },
    { firstname: "ندا", lastname: "افضل نیا", company: "" },
    { firstname: "پیمان", lastname: "بهمن", company: "آسیاتک" },
    { firstname: "محمد حسین", lastname: "دانائیان", company: "آسیاتک" },
    { firstname: "امیر", lastname: "رمزی", company: "آسیاتک" },
    { firstname: "افسون", lastname: "بهپور", company: "SOS" },
    { firstname: "حامد", lastname: "اسدنژاد", company: "آسیاتک" },
    { firstname: "فرشاد", lastname: "قلی زاده", company: "آسیاتک" },
    { firstname: "فرزین", lastname: "بروجردی", company: "digikala" },
    { firstname: "مسعود", lastname: "خلیل نژاد", company: "آسیاتک" },
    { firstname: "احسان", lastname: "کريمي آهويي", company: "پارس آنلاین" },
    { firstname: "مرتضی", lastname: "رحیمی", company: "پیوند آزاد شبکه" },
    { firstname: "منوچهر", lastname: "هاشم لو", company: "" },
    { firstname: "ابراهیم", lastname: "کشی زاده", company: "رسپینا" },
    { firstname: "مجتبی", lastname: "گلزاری هویدا", company: "" },
    { firstname: "محمد صادق", lastname: "عطار", company: "زرماکارون" },
    { firstname: "کاظم", lastname: "فلاحی", company: "" },
    { firstname: "امیرمحمد", lastname: "فاتح", company: "وب ایده" },
    { firstname: "رضا", lastname: "شالباف‌زاده", company: "" },
    { firstname: "حسین", lastname: "فرجی", company: "آسیاتک" },
    { firstname: "ارشاد", lastname: "میردامادی", company: "KMD Group" },
    {
      firstname: "مسعود",
      lastname: "اربابي",
      company: "زيرساخت امن خدمات تراكنشي",
    },
    { firstname: "مهرداد", lastname: "مرتضوی", company: "پرتو آبی" },
    { firstname: "بهمن", lastname: "جعفری", company: "رایان هم افزا" },
    { firstname: "حمید", lastname: "صفری", company: "افرانت" },
    { firstname: "محمد", lastname: "قليزاده", company: "باران تلكام" },
    {
      firstname: "امیر محمد",
      lastname: "مقدم فر",
      company: "خدمات ارتباطات شبکه علمی ایران (شعا)",
    },
    { firstname: "میلاد", lastname: "استادیان", company: "هاست ایران" },
    {
      firstname: "علیرضا",
      lastname: "غفراللهی",
      company: "خدمات ارتباطات شبکه علمی ایران (شعا)",
    },
    { firstname: "زهرا", lastname: "کریمی تبار", company: "" },
    { firstname: "محمدمهدی", lastname: "اشتری", company: "های وب" },
    { firstname: "مرتضی", lastname: "برجی", company: "بهارتل" },
    { firstname: "مرتضی", lastname: "برجی", company: "بهارتل" },
    {
      firstname: "قاسم",
      lastname: "صدری",
      company: "سازمان پژوهش ها وزارت علوم",
    },
    {
      firstname: "حسین",
      lastname: "باقرپور",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "محمد امین", lastname: "کریمان شاددل", company: "" },
    { firstname: "دانیال", lastname: "گردی", company: "کافه بازار" },
    { firstname: "محمدرضا", lastname: "ظریف سلطانی", company: "مشهدهاست" },
    {
      firstname: "امیر",
      lastname: "بهروان",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "محمد", lastname: "برومندفر", company: "دیده بان نت" },
    { firstname: "زهره", lastname: "چیزاری", company: "" },
    { firstname: "مسعود", lastname: "سلطانی فرسنگی", company: "دیده بان نت" },
    { firstname: "امیرخاتم", lastname: "پدرام", company: "" },
    { firstname: "مهدی", lastname: "پندارش", company: "شبدیز" },
    { firstname: "امین", lastname: "رازی", company: "رای‌نت" },
    { firstname: "محسن", lastname: "شهبازی", company: "رای‌نت" },
    { firstname: "حسن", lastname: "فولادی", company: "داده پردازی رسپینا" },
    { firstname: "شایان", lastname: "موسوی", company: "آسیاتک" },
    { firstname: "مصطفی", lastname: "سدفی", company: "کاوشگرنوین کارآمد" },
    { firstname: "آرش", lastname: "حقیقت", company: "فناپ پرداخت" },
    { firstname: "محمد حسین", lastname: "افتخاری", company: "" },
    {
      firstname: "پیمان",
      lastname: "کازرانی فراهانی",
      company: "موتور جستجوی ویز",
    },
    { firstname: "رضا", lastname: "حاج واحدی", company: "" },
    { firstname: "مبین", lastname: "نظری منتظر", company: "شاتل" },
    { firstname: "وحیدرضا", lastname: "اخلاص", company: "" },
    { firstname: "مهدی", lastname: "تکلو", company: "سپهرسبز خاورمیانه" },
    { firstname: "ابراهیم", lastname: "دریا", company: "" },
    {
      firstname: "فرشاد",
      lastname: "اسماعیلیان",
      company: "نوآوران شبکه سبز مهرگان (هاست ایران)",
    },
    { firstname: "خدیجه", lastname: "زاهدی", company: "شرکت مخابرات ایران" },
    { firstname: "حسن", lastname: "جامعی", company: "شرکت مخابرات ایران" },
    { firstname: "علیرضا", lastname: "وزیری", company: "" },
    { firstname: "محمد حسین", lastname: "زاده عباس", company: "" },
    { firstname: "محمد", lastname: "مرادی", company: "مبنا تلکام" },
    { firstname: "کوروش", lastname: "تفرشی", company: "ابر آروان" },
    { firstname: "علیرضا", lastname: "صائبی", company: "فن آوا" },
    { firstname: "حمیدرضا", lastname: "رضایی", company: "" },
    {
      firstname: "مهدي",
      lastname: "صالحي مقدم",
      company: "نيكان ارتباطات شهر",
    },
    {
      firstname: "علی اکبر",
      lastname: "خان محمدی",
      company: "داده پردازی رسپینا",
    },

    { firstname: "مهراد", lastname: "مهرکام", company: "ارتباطات زیرساخت" },
    { firstname: "حسین", lastname: "خرمی", company: "صدا و سیما" },
    { firstname: "مهدی", lastname: "حضرتی", company: "مخابرات ایران" },
    { firstname: "مجید", lastname: "عیسی لو", company: "میزیان داده پاسارگاد" },
    {
      firstname: "امین",
      lastname: "محمدی ها",
      company: "شرکت داده پردازی رسپینا",
    },
    { firstname: "وحید", lastname: "شهبازیان", company: "" },
    { firstname: "یوسف", lastname: "نعیمی", company: "آسیاتک" },
    { firstname: "محسن", lastname: "محمدی", company: "آسیاتک" },
    {
      firstname: "سمانه سادات",
      lastname: "هاشمی پور",
      company: "شرکت ارتباطات زیرساخت",
    },
    { firstname: "پوریا", lastname: "قائدی", company: "یکتا ارتباط" },
    { firstname: "بهنام", lastname: "یزدانی", company: "آسیاتک" },
    { firstname: "محمدرضا", lastname: "روشن", company: "افرانت" },
    { firstname: "احمد", lastname: "حسینی", company: "" },
    { firstname: "سعید", lastname: "نیاکان لاهیجی", company: "" },
    { firstname: "حمید", lastname: "خزلی", company: "" },
    { firstname: "امیر", lastname: "جاویدان", company: "ارتباطات شبکه دی" },
    { firstname: "محمد علی", lastname: "حاجیان", company: "مبنا تلکام" },
    { firstname: "گرشا", lastname: "نورى خواه", company: "روان ارتباط" },
    {
      firstname: "علی",
      lastname: "رحمان پور",
      company: "راهبران اینترنت اشیا (لینکپ)",
    },
    { firstname: "عرفان", lastname: "طاهرخانی", company: "linksp" },
    { firstname: "محمد", lastname: "مرادی", company: "مبنا تلکام" },
    { firstname: "اميد", lastname: "محمدي", company: "برليان نت" },
    { firstname: "رضا", lastname: "واحدی", company: "آسیاتک" },
    { firstname: "آرش", lastname: "خاجوی", company: "روان ارتباط عصر" },
    {
      firstname: "ابراهیم",
      lastname: "مامانی",
      company: "رساناپیشتاز - ارتباطات ثابت پارسیان",
    },
    { firstname: "علی", lastname: "ابنیکی", company: "" },
    { firstname: "امید", lastname: "واحد وخشوری", company: "چکاد" },
    { firstname: "علیرضا", lastname: "حبیبی", company: "شبکه گستر کایر" },
    { firstname: "رضا", lastname: "گنجی", company: "نقش اول کیفیت" },
    { firstname: "محمد", lastname: "ضربعلی زاده", company: "فناپ تلکام" },
    { firstname: "محمد", lastname: "ضربعلی زاده", company: "فناپ تلکام" },
    { firstname: "حسن", lastname: "فولادی", company: "داده پردازی رسپینا" },
    {
      firstname: "مریم",
      lastname: "زارعیان جهرمی",
      company: "سرزمین فناوری شبکه ستارگان",
    },
    { firstname: "مرتضی", lastname: "سلطانی", company: "سینداد" },
    { firstname: "رضا", lastname: "جمالی", company: "سینداد" },
    { firstname: "حبیب", lastname: "کمایی", company: "پارس الکتریک" },
    { firstname: "محمدرضا", lastname: "رفعت دلیوند", company: "" },
    { firstname: "علی", lastname: "میربهاالدین طهرانی", company: "زیر ساخت" },
    { firstname: "آزاده", lastname: "پزشکی", company: "داده پردازی رسپینا" },
    {
      firstname: "علی",
      lastname: "زعیم کهن",
      company: "شرکت ارتباطات زیرساخت",
    },
    {
      firstname: "حسن",
      lastname: "مرزدار",
      company: "شرکت ارتباطات سیار ایران MCI",
    },
    { firstname: "ابراهیم", lastname: "دریا", company: "" },
    { firstname: "مینا", lastname: "رضایی", company: "" },
    {
      firstname: "ایوب",
      lastname: "بنیادی",
      company: "شرکت ارتباطات سیار ایران MCI",
    },
    {
      firstname: "سید علی",
      lastname: "مروج",
      company: "شرکت ارتباطات سیار ایران MCI",
    },
    { firstname: "پوریا", lastname: "جعفری", company: "وزارت جهادکشاورزی" },
    { firstname: "سیامک", lastname: "محسنی", company: "زیرساخت" },
    {
      firstname: "نیلوفر",
      lastname: "کیایی",
      company: "Respina Network & Beyond",
    },
    {
      firstname: "افشین",
      lastname: "واعظی",
      company: "Respina Network & Beyond",
    },
    {
      firstname: "میثم",
      lastname: "رحمتیان",
      company: "راهکار داده پرداز کهن",
    },
    {
      firstname: "احسان",
      lastname: "رحمتیان ماسوله",
      company: "راهکار داده پرداز کهن",
    },
    { firstname: "میلاد", lastname: "مومنی", company: "آبان" },
    { firstname: "شهاب", lastname: "احمدپور", company: "های وب" },
    {
      firstname: "محمد حسین",
      lastname: "مهندس",
      company: "سازمان فناوری اطلاعات شهرداری تهران",
    },
    { firstname: "شهاب", lastname: "احمدپور", company: "های وب" },
    { firstname: "آیدا", lastname: "شیربازو", company: "های وب" },
    { firstname: "هادی", lastname: "کنطورچیان", company: "" },
    { firstname: "فاطمه", lastname: "مهدوی", company: "" },
    { firstname: "سعید", lastname: "حیدری", company: "داده پردازی رسپینا" },
    { firstname: "رامین", lastname: "انصاری", company: "" },
    { firstname: "پرشنگ", lastname: "مولائی", company: "" },
    { firstname: "مسعود", lastname: "هداوند", company: "داده پردازی رسپینا" },
    {
      firstname: "سید علیرضا",
      lastname: "میراحمدی",
      company: "داده پردازی رسپینا",
    },
    { firstname: "شهرزاد", lastname: "نورزاد", company: "فناپ" },
    { firstname: "سید مجید", lastname: "هاشمی", company: "بهاران" },
    { firstname: "آیدا", lastname: "شیربازو", company: "های وب" },
    { firstname: "علیرضا", lastname: "شریف پور", company: "شاتل" },
    { firstname: "ابوالفضل", lastname: "محسنی", company: "شاتل" },
    { firstname: "محمد حسین", lastname: "زاده عباس", company: "" },
    { firstname: "سعید", lastname: "محسنی", company: "افرا ارتاباطات رسا" },
    {
      firstname: "کیوان",
      lastname: "محمدی",
      company: "داده پردازان سبز البرز",
    },
    { firstname: "مهدی", lastname: "مقصودی", company: "دیده بان نت" },
    { firstname: "سهیل", lastname: "شهسواری", company: "دیده بان نت" },
    {
      firstname: "Ali",
      lastname: "Khederzadh",
      company: "توسعه ارتباطات نور اروند",
    },
    { firstname: "Ali", lastname: "Ahmadi", company: "" },
    { firstname: "زهرا", lastname: "کریمی تبار", company: "" },
    { firstname: "حمید", lastname: "سلطانی", company: "" },
    { firstname: "حمید", lastname: "سلطانی", company: "" },
    {
      firstname: "امیر محمد",
      lastname: "صنایعیان",
      company: "شرکت ملی گاز ایران",
    },
    {
      firstname: "حامد",
      lastname: "اخوان فر",
      company: "پیشگامان توسعه ارتباطات",
    },
    {
      firstname: "حامد",
      lastname: "اخوان فر",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "بهمن", lastname: "جعفری", company: "رایان هم افزا" },
    { firstname: "آرش", lastname: "پارساپور", company: "دیجیاتو" },
    { firstname: "مسعود", lastname: "مقصودی", company: "" },
    { firstname: "مهدیه", lastname: "نصیری", company: "گسترش ارتباطات مبنا" },
    { firstname: "عادل", lastname: "شاهینی", company: "ارتباطات ثابت پارسیان" },
    { firstname: "صادق", lastname: "ترکیبی", company: "آسیاتک" },
    { firstname: "محمد", lastname: "کاظمی", company: "گسترش ارتباطات مبنا" },
  ],
};
