import { IrnogEvent } from "../types";

export const Irnog4: IrnogEvent = {
  title: "دومین",
  time: "دوشنبه - 26 آذرماه 1397",
  location: {
    country: "ایران",
    city: "تهران",
    detail: "مرکز همایش های بین المللی رایزن",
    locationLink:
      "https://www.google.com/maps/dir//Rayzan+International+Conference+Centre+Tehran+Province,+Tajrish+Unnamed+Road+RF8J%2BMR4/@35.8166345,51.4820754,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3f8e1acef7932ab3:0xa96dea0f6e2efda6!2m2!1d51.4820754!2d35.8166345?entry=ttu&g_ep=EgoyMDI1MDMwOC4wIKXMDSoASAFQAw%3D%3D",
  },
  irnogAgenda: [
    {
      presenter: "شاهین غرقی",
      presentationTitle: "افتتاحیه",
      presentationLink: "https://www.aparat.com/v/f76gj5s",
    },
    {
      presenter: "Vahan Hovsepyan",
      presentationTitle: "RIPE NCC Update",
      presentationLink: "https://www.aparat.com/v/a89vz",
    },
    {
      presenter: "علیرضا وزیری",
      presentationTitle: "روش‌های کنترل سوء استفاده رایانه‌ای",
      presentationLink: "https://www.aparat.com/v/u55bzat ",
    },
    {
      presenter: "میلاد افشاری",
      presentationTitle: "RIPE Atlas statistics in Iran and the world",
      presentationLink: "https://www.aparat.com/v/NqFQL",
    },
    {
      presenter: "پوریا موسوی‌زاده",
      presentationTitle: "Decentralizing Internet Infrastructure",
      presentationLink: "https://www.aparat.com/v/q0D8K",
    },
    {
      presenter: "احسان قاضی‌زاده",
      presentationTitle: "BGPSEC",
      presentationLink: "https://www.aparat.com/v/q1R9G",
    },
    {
      presenter: "محمد خطیبی",
      presentationTitle: "The Iranian NOG",
      presentationLink: "https://www.aparat.com/v/j517p8l",
    },
    {
      presenter: "امید کوثری",
      presentationTitle: "Cache, the Good, the Bad and the Ugly",
      presentationLink: "https://www.aparat.com/v/r477r40",
    },
    {
      presenter: "کاظم فلاحی",
      presentationTitle: "حمله DNS",
      presentationLink: "https://www.aparat.com/v/f227oor",
    },
    {
      presenter: "میلاد افشاری",
      presentationTitle: "اختتامیه",
      presentationLink: "https://www.aparat.com/v/bjg32",
    },
  ],
  sponsers: {
    platinumSponsors: [
      {
        logo: "/logo/sponsers/irnog2/ncc.png",
        link: "https://www.ripe.net/",
        name: "RIPE NCC",
      },
      {
        logo: "/logo/sponsers/irnog2/world communications development.jpg",
        link: "#",
        name: "world communications development",
      },
    ],
    moralSponsor: [
      {
        logo: "/logo/sponsers/irnog2/webcheen.png",
        link: "http://www.webcheen.com/",
        name: "webCheen",
      },
    ],
  },
  Participants: [
    {
      firstname: "میلاد",
      lastname: "افشاری",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    {
      firstname: "مرتضی",
      lastname: "سلطانی",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    {
      firstname: "محمد",
      lastname: "خطیبی",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    {
      firstname: "سیدپوریا",
      lastname: "موسوی‌زاده تهرانی",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    {
      firstname: "شهاب",
      lastname: "وهابزاده",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    {
      firstname: "پارسا",
      lastname: "یوسفی",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    { firstname: "Arian", lastname: "Ramezani", company: "" },
    { firstname: "Ehsan", lastname: "Ghazizadeh", company: "Cafe Bazaar" },
    { firstname: "Farshad", lastname: "Vakili", company: "Pejvak" },
    { firstname: "Kh", lastname: "Kohansal", company: "" },
    { firstname: "Mohammadreza", lastname: "Kiani", company: "" },
    { firstname: "Shima", lastname: "Ghasemi", company: "" },
    { firstname: "Yousef", lastname: "Naimi", company: "" },
    { firstname: "ابراهیم", lastname: "پنج میر", company: "شرکت تولیدی شیوا" },
    { firstname: "ابراهیم", lastname: "کشی زاده", company: "ابرآروان" },
    { firstname: "ابراهیم", lastname: "مجتبایی", company: "رسپینا" },
    { firstname: "ابوالفضل", lastname: "نجفی", company: "ایرانسل" },
    { firstname: "احسان", lastname: "زینلیان زاده", company: "ایفاسرام" },
    {
      firstname: "احسان",
      lastname: "رحمتیان",
      company: "راهکار داده پرداز کهن",
    },
    { firstname: "احسان", lastname: "الهامی", company: "راتین پردازش دانا" },
    { firstname: "احسان", lastname: "مومنی", company: "داده‌ورزی سداد" },
    { firstname: "احمد", lastname: "نویدی", company: "پیشگامان" },
    { firstname: "احسان", lastname: "باوندپور", company: "افرانت" },
    { firstname: "آرزو", lastname: "محمدی", company: "گلرنگ سیستم" },
    { firstname: "ارشاد", lastname: "مختاری", company: "هیراد" },
    { firstname: "اصلان", lastname: "تبریا", company: "گسترش داده پردازی آوا" },
    { firstname: "افشین", lastname: "واعظی", company: "" },
    { firstname: "اکرم", lastname: "بهادری", company: "" },
    { firstname: "الهام", lastname: "نوربخش", company: "هیژا دارو" },
    { firstname: "الهه", lastname: "آجرلو", company: "آسیاتک" },
    { firstname: "امید", lastname: "شفقی امام", company: "ارتباط گستر egt" },
    { firstname: "امید", lastname: "دهقان", company: "" },
    { firstname: "امیر", lastname: "فولادوند", company: "پردیس" },
    { firstname: "امیر", lastname: "مهدی پور", company: "پنتا سرور" },
    { firstname: "امیر", lastname: "صفری فروشانی", company: "دورانتاش" },
    {
      firstname: "امیر",
      lastname: "اکبری زاده",
      company: "گسترش ارتباطات صبا",
    },
    { firstname: "امیر", lastname: "اثناعشری", company: "ASD Group" },
    { firstname: "امیر حسین", lastname: "ثابت", company: "صفرویک پرداز" },
    { firstname: "امیر عباس", lastname: "زارع", company: "همراه اول" },
    { firstname: "امیر محمد", lastname: "فاتح", company: "راتین پردازش" },
    {
      firstname: "امیرحسین",
      lastname: "کامرانی",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "امیرحسین", lastname: "تابش", company: "" },
    { firstname: "امیرحسین", lastname: "سلطان زاده", company: "ناواکو" },
    {
      firstname: "امیرحسین",
      lastname: "رحمتیان ماسوله",
      company: "بانک خاورمیانه",
    },
    { firstname: "امیرحسین", lastname: "تابش", company: "" },
    { firstname: "امیرحسین", lastname: "نعمت زاده", company: "بارزپخش" },
    { firstname: "امیرحسین", lastname: "احمدی", company: "ایرانیکاسرور" },
    { firstname: "امیرحسین", lastname: "فروزانی", company: "Networkfa.net" },
    { firstname: "امیرحسین", lastname: "باستانی", company: "برتینا" },
    { firstname: "امیرخاتم", lastname: "پدرام", company: "دیده بان نت" },
    { firstname: "امیررضا", lastname: "شریفی", company: "پرهام سیستم" },
    {
      firstname: "امین",
      lastname: "حمیدی یونسی",
      company: "شرکت ملی نفت ایران",
    },
    { firstname: "امین", lastname: "آسوده فرد جهرمی", company: "" },
    { firstname: "امین", lastname: "ملک قاسمی", company: "آترین" },
    { firstname: "امین", lastname: "سیفی", company: "لایزر" },
    { firstname: "امین", lastname: "دهباشی", company: "افرانت" },
    { firstname: "امین رضا", lastname: "فرنیا", company: "افرانت" },
    { firstname: "اندیشه", lastname: "داداش زاده", company: "رهیارسرور" },
    { firstname: "ایمان", lastname: "شباهنگ", company: "خانه امنیت حافظ" },
    { firstname: "ایمان", lastname: "کمالی", company: "" },
    { firstname: "ایمان", lastname: "فرهی پرشگفتی", company: "فرکیان تک" },
    { firstname: "آرزو", lastname: "کاظمی مقدس", company: "بانک پاسارگاد" },
    { firstname: "آرش", lastname: "راست پور", company: "آسیاتک" },
    { firstname: "آرش", lastname: "رضایی", company: "" },
    { firstname: "آرش", lastname: "جلالی", company: "سینداد" },
    { firstname: "آرش", lastname: "رجبی", company: "" },
    { firstname: "آرمین", lastname: "سخاجو", company: "" },
    {
      firstname: "آریا",
      lastname: "جهانگیری فر",
      company: "شرکت مهندسی صفر و یک پرداز",
    },
    { firstname: "آرین", lastname: "اقبال", company: "" },
    { firstname: "آزاده", lastname: "پزشکی", company: "کاسپین" },
    { firstname: "بابک", lastname: "علمدار", company: "توسعه ارتباطات داناک" },
    { firstname: "بهار", lastname: "ضمیری", company: "" },
    { firstname: "بهروز", lastname: "قادری", company: "هایلینک" },
    { firstname: "بهروز", lastname: "غفوریان", company: "Behsa" },
    {
      firstname: "بهزاد",
      lastname: "آتش فشان",
      company: "دانشگاه علوم توانبخشی و سلامت اجتماعی",
    },
    { firstname: "بهشاد", lastname: "رضایی", company: "تک نت" },
    { firstname: "بهمن", lastname: "جعفری", company: "رایان هم افزا" },
    { firstname: "بهنام", lastname: "ولی‌زاده", company: "" },
    { firstname: "بهنام", lastname: "نامور", company: "هرمز نت" },
    { firstname: "بهنام", lastname: "یزدانی", company: "" },
    { firstname: "بهنام", lastname: "بهادری", company: "" },
    { firstname: "بهنود", lastname: "هلیلیان", company: "رایانمهر دانش سنج" },
    { firstname: "پدرام", lastname: "قفقازی", company: "مبناتلکام" },
    { firstname: "پژمان", lastname: "رابطی", company: "شبدیز" },
    { firstname: "پوریا", lastname: "جلال پور", company: "" },
    { firstname: "پویا", lastname: "رضائی فر", company: "نوبر سبز" },
    { firstname: "پیمان", lastname: "پیمان نژاد", company: "" },
    { firstname: "تارا", lastname: "بجنوردی", company: "آسیاتک" },
    { firstname: "حامد", lastname: "قربانزاده", company: "مهرگان نت" },
    { firstname: "حامد", lastname: "سلامی", company: "" },
    { firstname: "حامد", lastname: "مالکی", company: "علی بابا" },
    { firstname: "حامد", lastname: "خرم یار", company: "Aivivid AB" },
    { firstname: "حسن", lastname: "اسکندری", company: "چکاوک" },
    { firstname: "حسن", lastname: "قاسمی", company: "سریع سیستم جنوب" },
    { firstname: "حسن", lastname: "جباری", company: "افرانت" },
    { firstname: "حسن", lastname: "فولادی", company: "رهیاب رایانه گستر" },
    { firstname: "حسین", lastname: "فرمهینی", company: "" },
    { firstname: "حسین", lastname: "ناظری", company: "افرانت" },
    { firstname: "حسین", lastname: "برومند", company: "آتیه آفرینان" },
    { firstname: "حسین", lastname: "زاهدی", company: "آریاسرور" },
    {
      firstname: "حسین",
      lastname: "باقرپور",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "حسین", lastname: "ذاکر", company: "انتقال داده ماهان" },
    { firstname: "حسین", lastname: "یوسفی", company: "" },
    {
      firstname: "حسین",
      lastname: "حاتمی کاکش",
      company: "مرکز اطلاع رسانی نیوشا",
    },
    { firstname: "حسین", lastname: "بحری", company: "لایزر" },
    { firstname: "حسین", lastname: "میرزائی", company: "" },
    { firstname: "حسین", lastname: "علی تبار", company: "ایرانسل" },
    { firstname: "حمید", lastname: "نعیم آبادی", company: "آواکتان" },
    { firstname: "حمید", lastname: "صفری", company: "افرانت" },
    {
      firstname: "حمید رضا",
      lastname: "رضایی",
      company: "نوین رایان پردیس کاوه",
    },
    { firstname: "حمیدرضا", lastname: "قربانی رز", company: "همراه اول" },
    { firstname: "حمیدرضا", lastname: "صفرپور", company: "داده پردازی مبین" },
    { firstname: "حمیدرضا", lastname: "قوامیان", company: "اسیاتک" },
    {
      firstname: "خدیجه",
      lastname: "زاهدی آرانی",
      company: "شرکت مخابرات ایران",
    },
    { firstname: "دانیال", lastname: "مهجورثانی", company: "" },
    { firstname: "داود", lastname: "زارع مویدی", company: "رامک" },
    { firstname: "داویت", lastname: "داودیان", company: "سینداد" },
    { firstname: "دلارام", lastname: "مهدوی", company: "" },
    { firstname: "ذبیح الله", lastname: "داوری", company: "یوزنت" },
    { firstname: "رحیم", lastname: "عباس زاده", company: "جهان سبز مهر" },
    { firstname: "رسول", lastname: "مهرعلی", company: "" },
    { firstname: "رضا", lastname: "جعفری", company: "" },
    { firstname: "رضا", lastname: "محمدی", company: "ویوا رایانه" },
    { firstname: "رضا", lastname: "واحدی", company: "پیشگامان توسعه ارتباطات" },
    { firstname: "رضا", lastname: "خالواکبری", company: "ایرانسل" },
    { firstname: "رضا", lastname: "زند", company: "" },
    { firstname: "رضا", lastname: "خواجوی", company: "سیمرغ" },
    { firstname: "رضا", lastname: "جمالی", company: "فناوران شبکه سینداد" },
    { firstname: "رضا", lastname: "بهروزی", company: "" },
    { firstname: "رضا", lastname: "طالبی", company: "رسیس" },
    { firstname: "رضا", lastname: "پناهی سهرابلو", company: "مبنا تلکام" },
    { firstname: "رضا", lastname: "مرادی", company: "ایمن داده پرهام" },
  ],
};
