import { IrnogEvent } from "../types";

export const Irnog4: IrnogEvent = {
  title: "اولین",
  time: `پنجشنبه - 14 تیر ماه 1403`,
  location: {
    country: "ایران",
    city: "تهران",
    detail: "خیابان شریعتی، سالن کنفرانس پیام سوم ",
    locationLink: "google.com",
  },
  irnogAgenda: [
    {
      presenter: "مهدی",
      presentationTitle: "یاضی",
      presentationTime: "10min",
      presentationLink: "youtube.com",
    },
    {
      presenter: "مهدی",
      presentationTitle: "ریاضی",
      presentationTime: "10min",
      presentationLink: "youtube.com",
    },
    {
      presenter: "مهدی",
      presentationTitle: "ریاضی",
      presentationTime: "10min",
      presentationLink: "youtube.com",
    },
    {
      presenter: "مهدی",
      presentationTitle: "ریاضی",
      presentationTime: "10min",
      presentationLink: "youtube.com",
    },
    {
      presenter: "مهدی",
      presentationTitle: "ریاضی",
      presentationTime: "10min",
      presentationLink: "youtube.com",
    },
    {
      presenter: "مهدی",
      presentationTitle: "ریاضی",
      presentationTime: "10min",
      presentationLink: "youtube.com",
    },
    {
      presenter: "مهدی",
      presentationTitle: "ریاضی",
      presentationTime: "10min",
      presentationLink: "youtube.com",
    },
    {
      presenter: "مهدی",
      presentationTitle: "ریاضی",
      presentationTime: "10min",
      presentationLink: "youtube.com",
    },
  ],
  sponsers: {
    hostSponsors: {
      logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
      link: "google.com",
      name: "google",
    },
    platinumSponsors: [
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
    ],
    goldSponsors: [
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
    ],
    silverSponsors: [
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
    ],
    ConnectivitySponsors: [
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
    ],
    moralSponsor: [
      {
        logo: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg",
        link: "google.com",
        name: "google",
      },
    ],
  },
  gallery: [
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
    { image: "https://www.irnog.net/wp-content/uploads/2017/10/38.jpg" },
  ],

  Participants: [
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
    { firstname: "مهدی", lastname: "مظلوم", company: "هوپاد" },
  ],
};
