import { IrnogEvent } from "../types";

export const Irnog4: IrnogEvent = {
  title: "چهارمین",
  time: "پنجشنبه - 14 بهمن ماه 1400",
  location: {
    country: "ایران",
    city: "تهران",
    detail:
      "تهران، خیابان شیخ بهایی جنوبی، شهرک والفجر، خیابان ایرانشناسی، خیابان نهم، پلاک 6 ، مرکز همایشهای سازمان مدیریت صنعتی ",
    locationLink:
      "https://www.ghttps://www.google.com/maps/dir//%D9%85%D8%B1%DA%A9%D8%B2+%D8%B2%D8%A8%D8%A7%D9%86+%D8%B3%D8%A7%D8%B2%D9%85%D8%A7%D9%86+%D9%85%D8%AF%DB%8C%D8%B1%DB%8C%D8%AA+%D8%B5%D9%86%D8%B9%D8%AA%DB%8C+P9WR%2BJ87+District+6+Tehran+Tehran+Province%E2%80%AD%E2%80%AD/@35.7465286,51.390794,18z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3f8e06e06f039141:0xaac808855972f686!2m2!1d51.390794!2d35.7465286?entry=ttu&g_ep=EgoyMDI1MDMxMi4wIKXMDSoASAFQAw%3D%3Doogle.com/maps/dir//%D9%85%D8%B1%DA%A9%D8%B2+%D8%B2%D8%A8%D8%A7%D9%86+%D8%B3%D8%A7%D8%B2%D9%85%D8%A7%D9%86+%D9%85%D8%AF%DB%8C%D8%B1%DB%8C%D8%AA+%D8%B5%D9%86%D8%B9%D8%AA%DB%8C+P9WR%2BJ87+District+6+Tehran+Tehran+Province%E2%80%AD%E2%80%AD/@35.7465286,51.390794,18z/data=!4m8!4m7!1m0!1m5!1m1!1s0x3f8e06e06f039141:0xaac808855972f686!2m2!1d51.390794!2d35.7465286?entry=ttu&g_ep=EgoyMDI1MDMxMi4wIKXMDSoASAFQAw%3D%3D",
  },
  irnogAgenda: [
    {
      presenter: "میلاد افشاری",
      presentationTitle: "افتتاحیه",
      presentationLink: "-",
    },
    {
      presenter: "شرکت‌های سینداد و هم روش",
      presentationTitle: "سخنرانی حامیان پلاتینیوم رویداد",
      presentationLink: "-",
    },
    {
      presenter: "حسن جباری",
      presentationTitle: "DCIM",
      presentationLink: "-",
    },
    {
      presenter: "Hisham Ibrahim",
      presentationTitle: "RIPE NCC Community Update",
      presentationLink: "-",
    },
    {
      presenter: "سید پوریا موسوی‌زاده تهرانی",
      presentationTitle: "FreeBSD as SDWAN Edges",
      presentationLink: "-",
    },
    {
      presenter: "سید مهران خلدی",
      presentationTitle: "eBPF - Shaping the Future of Networking and Security",
      presentationLink: "-",
    },
    {
      presenter: "احسان قاضی زاده",
      presentationTitle: "Vxlan/EVPN Data Centers in a New Era",
      presentationLink: "-",
    },
    {
      presenter: "میلاد افشاری",
      presentationTitle: "Mutually Agreed Norms for Routing Security (MANRS)",
      presentationLink: "-",
    },
    {
      presenter: "اعضای پنل",
      presentationTitle: 'پنل گفت و گو با محوریت موضوع "زنان در تکنولوژی"',
      presentationLink: "-",
    },
    {
      presenter: "رضا خالواکبری",
      presentationTitle: "Segment Routing Overview",
      presentationLink: "-",
    },
    {
      presenter: "وحید شهبازیان",
      presentationTitle: "Layer 3 Hardware Offloading in RouterOS v7",
      presentationLink: "-",
    },
    {
      presenter: "-",
      presentationTitle:
        "گفت و گوهای کوتاه:\n- Mitigation Methods and Introduction to DDOS Attacks\n- SIEM, XDR, SOAR\n...",
      presentationLink: "-",
    },
    {
      presenter: "-",
      presentationTitle: "اختتامیه",
      presentationLink: "-",
    },
  ],

  sponsers: {
    platinumSponsors: [
      {
        logo: "/logo/sponsers/irnog2/ncc.png",
        link: "https://www.ripe.net/",
        name: "RIPE NCC",
      },
      {
        logo: "/logo/sponsers/irnog4/hamRavesh.jpg",
        link: "https://hamravesh.com/",
        name: "هم روش",
      },
      {
        logo: "",
        link: "https://sindad.com/",
        name: "فناوران شبکه سینداد",
      },
    ],
    goldSponsors: [
      {
        logo: "/logo/sponsers/irnog4/minirouter.png",
        link: "https://minirouter.ir/",
        name: "miniRouter",
      },
    ],

    silverSponsors: [
      {
        logo: "/logo/sponsers/irnog4/persianTech.png",
        link: "https://ptco.net/",
        name: "persianTech",
      },
      {
        logo: "/logo/sponsers/irnog4/afranet.png",
        link: "https://afranet.ir/fa",
        name: "afraNet",
      },
    ],
  },
  Participants: [
    {
      firstname: "میلاد",
      lastname: "افشاری",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    {
      firstname: "مرتضی",
      lastname: "سلطانی",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    {
      firstname: "محمد",
      lastname: "خطیبی",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    {
      firstname: "سیدپوریا",
      lastname: "موسوی‌زاده تهرانی",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    {
      firstname: "شهاب",
      lastname: "وهابزاده",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    {
      firstname: "پارسا",
      lastname: "یوسفی",
      company: "عضو کمیته برنامه‌ریزی ایرناگ",
    },
    { firstname: "Arian", lastname: "Ramezani", company: "" },
    { firstname: "Ehsan", lastname: "Ghazizadeh", company: "Cafe Bazaar" },
    { firstname: "Farshad", lastname: "Vakili", company: "Pejvak" },
    { firstname: "Kh", lastname: "Kohansal", company: "" },
    { firstname: "Mohammadreza", lastname: "Kiani", company: "" },
    { firstname: "Shima", lastname: "Ghasemi", company: "" },
    { firstname: "Yousef", lastname: "Naimi", company: "" },
    { firstname: "ابراهیم", lastname: "پنج میر", company: "شرکت تولیدی شیوا" },
    { firstname: "ابراهیم", lastname: "کشی زاده", company: "ابرآروان" },
    { firstname: "ابراهیم", lastname: "مجتبایی", company: "رسپینا" },
    { firstname: "ابوالفضل", lastname: "نجفی", company: "ایرانسل" },
    { firstname: "احسان", lastname: "زینلیان زاده", company: "ایفاسرام" },
    {
      firstname: "احسان",
      lastname: "رحمتیان",
      company: "راهکار داده پرداز کهن",
    },
    { firstname: "احسان", lastname: "الهامی", company: "راتین پردازش دانا" },
    { firstname: "احسان", lastname: "مومنی", company: "داده‌ورزی سداد" },
    { firstname: "احمد", lastname: "نویدی", company: "پیشگامان" },
    { firstname: "احسان", lastname: "باوندپور", company: "افرانت" },
    { firstname: "آرزو", lastname: "محمدی", company: "گلرنگ سیستم" },
    { firstname: "ارشاد", lastname: "مختاری", company: "هیراد" },
    { firstname: "اصلان", lastname: "تبریا", company: "گسترش داده پردازی آوا" },
    { firstname: "افشین", lastname: "واعظی", company: "" },
    { firstname: "اکرم", lastname: "بهادری", company: "" },
    { firstname: "الهام", lastname: "نوربخش", company: "هیژا دارو" },
    { firstname: "الهه", lastname: "آجرلو", company: "آسیاتک" },
    { firstname: "امید", lastname: "شفقی امام", company: "ارتباط گستر egt" },
    { firstname: "امید", lastname: "دهقان", company: "" },
    { firstname: "امیر", lastname: "فولادوند", company: "پردیس" },
    { firstname: "امیر", lastname: "مهدی پور", company: "پنتا سرور" },
    { firstname: "امیر", lastname: "صفری فروشانی", company: "دورانتاش" },
    {
      firstname: "امیر",
      lastname: "اکبری زاده",
      company: "گسترش ارتباطات صبا",
    },
    { firstname: "امیر", lastname: "اثناعشری", company: "ASD Group" },
    { firstname: "امیر حسین", lastname: "ثابت", company: "صفرویک پرداز" },
    { firstname: "امیر عباس", lastname: "زارع", company: "همراه اول" },
    { firstname: "امیر محمد", lastname: "فاتح", company: "راتین پردازش" },
    {
      firstname: "امیرحسین",
      lastname: "کامرانی",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "امیرحسین", lastname: "تابش", company: "" },
    { firstname: "امیرحسین", lastname: "سلطان زاده", company: "ناواکو" },
    {
      firstname: "امیرحسین",
      lastname: "رحمتیان ماسوله",
      company: "بانک خاورمیانه",
    },
    { firstname: "امیرحسین", lastname: "تابش", company: "" },
    { firstname: "امیرحسین", lastname: "نعمت زاده", company: "بارزپخش" },
    { firstname: "امیرحسین", lastname: "احمدی", company: "ایرانیکاسرور" },
    { firstname: "امیرحسین", lastname: "فروزانی", company: "Networkfa.net" },
    { firstname: "امیرحسین", lastname: "باستانی", company: "برتینا" },
    { firstname: "امیرخاتم", lastname: "پدرام", company: "دیده بان نت" },
    { firstname: "امیررضا", lastname: "شریفی", company: "پرهام سیستم" },
    {
      firstname: "امین",
      lastname: "حمیدی یونسی",
      company: "شرکت ملی نفت ایران",
    },
    { firstname: "امین", lastname: "آسوده فرد جهرمی", company: "" },
    { firstname: "امین", lastname: "ملک قاسمی", company: "آترین" },
    { firstname: "امین", lastname: "سیفی", company: "لایزر" },
    { firstname: "امین", lastname: "دهباشی", company: "افرانت" },
    { firstname: "امین رضا", lastname: "فرنیا", company: "افرانت" },
    { firstname: "اندیشه", lastname: "داداش زاده", company: "رهیارسرور" },
    { firstname: "ایمان", lastname: "شباهنگ", company: "خانه امنیت حافظ" },
    { firstname: "ایمان", lastname: "کمالی", company: "" },
    { firstname: "ایمان", lastname: "فرهی پرشگفتی", company: "فرکیان تک" },
    { firstname: "آرزو", lastname: "کاظمی مقدس", company: "بانک پاسارگاد" },
    { firstname: "آرش", lastname: "راست پور", company: "آسیاتک" },
    { firstname: "آرش", lastname: "رضایی", company: "" },
    { firstname: "آرش", lastname: "جلالی", company: "سینداد" },
    { firstname: "آرش", lastname: "رجبی", company: "" },
    { firstname: "آرمین", lastname: "سخاجو", company: "" },
    {
      firstname: "آریا",
      lastname: "جهانگیری فر",
      company: "شرکت مهندسی صفر و یک پرداز",
    },
    { firstname: "آرین", lastname: "اقبال", company: "" },
    { firstname: "آزاده", lastname: "پزشکی", company: "کاسپین" },
    { firstname: "بابک", lastname: "علمدار", company: "توسعه ارتباطات داناک" },
    { firstname: "بهار", lastname: "ضمیری", company: "" },
    { firstname: "بهروز", lastname: "قادری", company: "هایلینک" },
    { firstname: "بهروز", lastname: "غفوریان", company: "Behsa" },
    {
      firstname: "بهزاد",
      lastname: "آتش فشان",
      company: "دانشگاه علوم توانبخشی و سلامت اجتماعی",
    },
    { firstname: "بهشاد", lastname: "رضایی", company: "تک نت" },
    { firstname: "بهمن", lastname: "جعفری", company: "رایان هم افزا" },
    { firstname: "بهنام", lastname: "ولی‌زاده", company: "" },
    { firstname: "بهنام", lastname: "نامور", company: "هرمز نت" },
    { firstname: "بهنام", lastname: "یزدانی", company: "" },
    { firstname: "بهنام", lastname: "بهادری", company: "" },
    { firstname: "بهنود", lastname: "هلیلیان", company: "رایانمهر دانش سنج" },
    { firstname: "پدرام", lastname: "قفقازی", company: "مبناتلکام" },
    { firstname: "پژمان", lastname: "رابطی", company: "شبدیز" },
    { firstname: "پوریا", lastname: "جلال پور", company: "" },
    { firstname: "پویا", lastname: "رضائی فر", company: "نوبر سبز" },
    { firstname: "پیمان", lastname: "پیمان نژاد", company: "" },
    { firstname: "تارا", lastname: "بجنوردی", company: "آسیاتک" },
    { firstname: "حامد", lastname: "قربانزاده", company: "مهرگان نت" },
    { firstname: "حامد", lastname: "سلامی", company: "" },
    { firstname: "حامد", lastname: "مالکی", company: "علی بابا" },
    { firstname: "حامد", lastname: "خرم یار", company: "Aivivid AB" },
    { firstname: "حسن", lastname: "اسکندری", company: "چکاوک" },
    { firstname: "حسن", lastname: "قاسمی", company: "سریع سیستم جنوب" },
    { firstname: "حسن", lastname: "جباری", company: "افرانت" },
    { firstname: "حسن", lastname: "فولادی", company: "رهیاب رایانه گستر" },
    { firstname: "حسین", lastname: "فرمهینی", company: "" },
    { firstname: "حسین", lastname: "ناظری", company: "افرانت" },
    { firstname: "حسین", lastname: "برومند", company: "آتیه آفرینان" },
    { firstname: "حسین", lastname: "زاهدی", company: "آریاسرور" },
    {
      firstname: "حسین",
      lastname: "باقرپور",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "حسین", lastname: "ذاکر", company: "انتقال داده ماهان" },
    { firstname: "حسین", lastname: "یوسفی", company: "" },
    {
      firstname: "حسین",
      lastname: "حاتمی کاکش",
      company: "مرکز اطلاع رسانی نیوشا",
    },
    { firstname: "حسین", lastname: "بحری", company: "لایزر" },
    { firstname: "حسین", lastname: "میرزائی", company: "" },
    { firstname: "حسین", lastname: "علی تبار", company: "ایرانسل" },
    { firstname: "حمید", lastname: "نعیم آبادی", company: "آواکتان" },
    { firstname: "حمید", lastname: "صفری", company: "افرانت" },
    {
      firstname: "حمید رضا",
      lastname: "رضایی",
      company: "نوین رایان پردیس کاوه",
    },
    { firstname: "حمیدرضا", lastname: "قربانی رز", company: "همراه اول" },
    { firstname: "حمیدرضا", lastname: "صفرپور", company: "داده پردازی مبین" },
    { firstname: "حمیدرضا", lastname: "قوامیان", company: "اسیاتک" },
    {
      firstname: "خدیجه",
      lastname: "زاهدی آرانی",
      company: "شرکت مخابرات ایران",
    },
    { firstname: "دانیال", lastname: "مهجورثانی", company: "" },
    { firstname: "داود", lastname: "زارع مویدی", company: "رامک" },
    { firstname: "داویت", lastname: "داودیان", company: "سینداد" },
    { firstname: "دلارام", lastname: "مهدوی", company: "" },
    { firstname: "ذبیح الله", lastname: "داوری", company: "یوزنت" },
    { firstname: "رحیم", lastname: "عباس زاده", company: "جهان سبز مهر" },
    { firstname: "رسول", lastname: "مهرعلی", company: "" },
    { firstname: "رضا", lastname: "جعفری", company: "" },
    { firstname: "رضا", lastname: "محمدی", company: "ویوا رایانه" },
    { firstname: "رضا", lastname: "واحدی", company: "پیشگامان توسعه ارتباطات" },
    { firstname: "رضا", lastname: "خالواکبری", company: "ایرانسل" },
    { firstname: "رضا", lastname: "زند", company: "" },
    { firstname: "رضا", lastname: "خواجوی", company: "سیمرغ" },
    { firstname: "رضا", lastname: "جمالی", company: "فناوران شبکه سینداد" },
    { firstname: "رضا", lastname: "بهروزی", company: "" },
    { firstname: "رضا", lastname: "طالبی", company: "رسیس" },
    { firstname: "رضا", lastname: "پناهی سهرابلو", company: "مبنا تلکام" },
    { firstname: "رضا", lastname: "مرادی", company: "ایمن داده پرهام" },
    { firstname: "ریحانه", lastname: "جاویدی", company: "مخابرات ایران  " },
    {
      firstname: "زهرا",
      lastname: "دل افروز",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "زهرا", lastname: "خانی", company: "افرانت" },
    { firstname: "سپهر", lastname: "آریانژاد", company: "فناوران لوتوس البرز" },
    { firstname: "سپهر", lastname: "غلامحسینی", company: "افرارسا" },
    { firstname: "ستاره", lastname: "سپهر", company: "ایرانسل" },
    { firstname: "سجاد", lastname: "محتشم", company: "عصر نوین" },
    { firstname: "سجاد", lastname: "ناظران", company: "صداوسیما" },
    { firstname: "سجاد", lastname: "آینه کار", company: "ژرف نگر" },
    { firstname: "سروش", lastname: "زندی", company: "گروه مهندسی پویان" },
    { firstname: "سعید", lastname: "اسدی شهری", company: "ماهان نت" },
    { firstname: "سعید", lastname: "دیانی", company: "رسا الکترونیک هوشمند" },
    { firstname: "سعید", lastname: "بیضایی", company: "شیراز_شبکه" },
    { firstname: "سعید", lastname: "آوخ", company: "" },
    { firstname: "سهند", lastname: "حبیبی", company: "فینیکس (‌wallex.ir)" },
    { firstname: "سید احسان", lastname: "سید علی اکبر", company: "اسنپ" },
    {
      firstname: "سید احمد",
      lastname: "شاه نعمت االه یزدی",
      company: "هاست ایران",
    },
    {
      firstname: "سید کیارش",
      lastname: "گلستانه",
      company: "داده گستر پارمیس",
    },
    { firstname: "سید محمد صادق", lastname: "فقیه حسینی", company: "موج بهمن" },
    {
      firstname: "سید محمد مهدی",
      lastname: "ولوی",
      company: "فناوران شبکه سینداد",
    },
    { firstname: "سیدامیرعلی", lastname: "برقعی", company: "امن افزار هوپاد" },
    { firstname: "سیدشهروز", lastname: "ویژه", company: "لایزر" },
    { firstname: "سیدعلیرضا", lastname: "نمازی", company: "" },
    { firstname: "سیدمرتضی", lastname: "موسوی", company: "" },
    { firstname: "سینا", lastname: "قمری", company: "شبکه ظرح مدار ایرانیان" },
    { firstname: "سینا", lastname: "مطلق", company: "" },
    { firstname: "سینا", lastname: "میرورزنده", company: "لایزر" },
    { firstname: "سینا", lastname: "شیرپرور", company: "Afranet" },
    { firstname: "شاهین", lastname: "کاظمی", company: "صفرویک" },
    { firstname: "شایان", lastname: "موسوی", company: "خبره پرداز پارس" },
    { firstname: "شایان", lastname: "رضائی", company: "ابرآروان" },
    { firstname: "شبنم", lastname: "نیکانیک", company: "شرکت مخابرات ایران" },
    { firstname: "شهروز", lastname: "امیدوار", company: "های وب" },
    { firstname: "شهریار", lastname: "کاشانکی", company: "مخابرات ایران" },
    { firstname: "صابر", lastname: "قاسمی", company: "" },
    { firstname: "صادق", lastname: "نجاتی زاده", company: "" },
    { firstname: "عادل", lastname: "حمزه", company: "قند شهدای دزفول" },
    { firstname: "عادل", lastname: "شاهینی", company: "Freelancer" },
    { firstname: "عبدالرسول", lastname: "کمالیان فر", company: "کمال آموز" },
    { firstname: "عبدالعظیم", lastname: "رحيم پور", company: "پارسان نت خنج" },
    { firstname: "عظیم", lastname: "جاویدی", company: "" },
    { firstname: "علی", lastname: "محمدی", company: "نقش روز" },
    { firstname: "علی", lastname: "اسکندری", company: "دالان تامین فراپارس" },
    { firstname: "علی", lastname: "کابلی", company: "" },
    { firstname: "علی", lastname: "رعیت پور", company: "هوش گراف" },
    { firstname: "علی", lastname: "پریزاد", company: "" },
    { firstname: "علی", lastname: "فرشیدپور", company: "" },
    { firstname: "علی", lastname: "زاهدی", company: "دیده بان نت" },
    { firstname: "علی", lastname: "نواب زاده", company: "" },
    { firstname: "علی", lastname: "پرتوی", company: "افرانت" },
    { firstname: "علی", lastname: "فلاح پور", company: "پتروشیمی اصفهان" },
    { firstname: "علی", lastname: "نیک‌نام", company: "پردیس" },
    { firstname: "علی", lastname: "مومن حجازی", company: "دیتاسنتر امین" },
    { firstname: "علی اكبر", lastname: "همتی", company: "" },
    { firstname: "علی اکبر", lastname: "اخوان آریج", company: "ابر آروان" },
    { firstname: "علیرضا", lastname: "انصافی", company: "گسترش فناوری" },
    { firstname: "علیرضا", lastname: "بهمنی", company: "افرانت" },
    {
      firstname: "علیرضا",
      lastname: "غزازانی",
      company: "ارتباطات هوشمند تبیان",
    },
    {
      firstname: "علیرضا",
      lastname: "باوی",
      company: "ارتباطات ثابت آوا اروند",
    },
    { firstname: "علیرضا", lastname: "نوروزی صفا", company: "لایزر" },
    { firstname: "علیرضا", lastname: "واحدی", company: "مبنا تلکام" },
    {
      firstname: "علیرضا",
      lastname: "غلام شاهی",
      company: "توسعه ارتباطات داناک",
    },
    { firstname: "عمید", lastname: "کاظمی", company: "" },
    { firstname: "فاطمه", lastname: "نظرمحمدی", company: "ماهنامه پیوست" },
    { firstname: "فاطمه", lastname: "مظاهریان", company: "" },
    { firstname: "فتاح", lastname: "شاکری حقیقی", company: "" },
    { firstname: "فرزاد", lastname: "حمدی", company: "شبکه ارتباطات لوناپارس" },
    { firstname: "فرزانه", lastname: "کبیریان", company: "رایانش" },
    { firstname: "فرزین", lastname: "آذری‌پور", company: "ابرآروان" },
    { firstname: "فرشاد", lastname: "منتخبی", company: "افرانت" },
    {
      firstname: "فرهاد",
      lastname: "فرجادمنش",
      company: "داده پردازی رایاسپهر",
    },
    {
      firstname: "فروتن",
      lastname: "بیانی",
      company: "نواندیشان ارتباط امن رسیس",
    },
    { firstname: "فری ماه", lastname: "چوبداری", company: "" },
    { firstname: "فرید", lastname: "ستاری", company: "هم‌روش" },
    { firstname: "فهیمه", lastname: "کاویانی", company: "DIGIFAHIM" },
    { firstname: "فواد", lastname: "بهزادی", company: "" },
    { firstname: "کیوان", lastname: "مأموری", company: "سینداد" },
    { firstname: "گلاره", lastname: "کلوانی", company: "" },
    { firstname: "لیلا", lastname: "تقوی فر", company: "" },
    { firstname: "ماهرخ", lastname: "نعمت‌ اللهی", company: "های‌وب" },
    { firstname: "مبین", lastname: "کوچک زاده", company: "مبین هاست" },
    {
      firstname: "مجتبی",
      lastname: "شهاب",
      company: "شرکت فناوری اطلاعات شهاب نت ساوه",
    },
    {
      firstname: "مجتبی",
      lastname: "سبزه ای",
      company: "فرا ارتباط کویر کاشان",
    },
    { firstname: "مجتبی", lastname: "منیعی", company: "تک نت" },
    { firstname: "مجید", lastname: "برزگر", company: "" },
    { firstname: "مجید", lastname: "عزیزی", company: "نتورکفا" },
    { firstname: "مجید", lastname: "محمدزاده", company: "داده پردازی رسپینا" },
    { firstname: "مجید", lastname: "میرزایی", company: "تکنو انرژی سپهر کیش" },
    {
      firstname: "محسن",
      lastname: "کربلاپی امینی",
      company: "امن افزار هوپاد",
    },
    { firstname: "محسن", lastname: "صیادجو", company: "" },
    { firstname: "محسن", lastname: "آقایی", company: "گروه مهندسی پویان" },
    { firstname: "محسن", lastname: "خوانساری", company: "" },
    { firstname: "محسن", lastname: "محمدی", company: "ایرانیکاسرور" },
    { firstname: "محسن", lastname: "مهدی پور", company: "افرانت" },
    { firstname: "محمد", lastname: "نجفی", company: "" },
    { firstname: "محمد", lastname: "کاظمی", company: "گسترش ارتباطات مبنا" },
    { firstname: "محمد", lastname: "حسنی", company: "دفتر کل کالا" },
    { firstname: "محمد", lastname: "سلیمی", company: "آسیاتک" },
    { firstname: "محمد", lastname: "برومندفر", company: "اوراتک" },
    { firstname: "محمد", lastname: "امین", company: "اطلس سیستم افق" },
    { firstname: "محمد", lastname: "دلفروز عبدالملکی", company: "پنتا سرور" },
    { firstname: "محمد", lastname: "ناصح", company: "لایزر" },
    { firstname: "محمد", lastname: "مرادی", company: "" },
    { firstname: "محمد", lastname: "محمد یعقوبی", company: "" },
    { firstname: "محمد", lastname: "ضربعلی زاده", company: "افرانت" },
    { firstname: "محمد", lastname: "صاحبدل", company: "صبا ایده" },
    {
      firstname: "محمد احسان",
      lastname: "طباخیان",
      company: "فیدار گستران شایا رایا",
    },
    { firstname: "محمد حسن", lastname: "هاشمی", company: "داده گستر پارمیس" },
    { firstname: "محمد رسول", lastname: "اکبری", company: "اندیشه سبز ماهان" },
    {
      firstname: "محمد رضا",
      lastname: "کریمی",
      company: "معاونت علمی و فناوری ریاست جمهوری",
    },
    { firstname: "محمد مهدی", lastname: "شفیعی", company: "" },
    { firstname: "محمد مهدی", lastname: "حسینی", company: "رسانه مهر وطن" },
    { firstname: "محمد میعاد", lastname: "علی کرمی", company: "" },
    { firstname: "محمدامین", lastname: "خطیبی", company: "" },
    { firstname: "محمدحسن", lastname: "جعفرزاده", company: "مبین هاست" },
    {
      firstname: "محمدرضا",
      lastname: "محرری",
      company: "توسعه و تدبیر جوامع سلام",
    },
    { firstname: "محمدرضا", lastname: "احمدی", company: "شرکت علی بابا" },
    {
      firstname: "محمدرضا",
      lastname: "ابرقویی",
      company: "آزادراه ساوه-سلفچگان",
    },
    {
      firstname: "محمدرضا",
      lastname: "ناظم",
      company: "مهندسی داده پردازان سپنتامهر",
    },
    { firstname: "محمدرضا", lastname: "دژم", company: "" },
    { firstname: "محمود", lastname: "سیدرضویان", company: "Hiweb" },
    { firstname: "مرتضی", lastname: "اعلم الهدی", company: "شرکت ایفاسرام" },
    { firstname: "مرتضی", lastname: "صادقی", company: "Aryahamrah" },
    { firstname: "مرتضی", lastname: "رضایی", company: "" },
    { firstname: "مرضیه", lastname: "لکزایی", company: "" },
    { firstname: "مریم", lastname: "معصومی", company: "" },
    { firstname: "مریم", lastname: "زارعیان جهرمی", company: "miniRouter" },
    { firstname: "مسعود", lastname: "سلطانی", company: "دیده بان نت" },
    { firstname: "مسعود", lastname: "خلیل نژاد", company: "" },
    { firstname: "مسعود", lastname: "رضیان", company: "زیرساخت(دوران)" },
    { firstname: "منوچهر", lastname: "هاشم لو", company: "اندیشه سبز ماهان" },
    { firstname: "مهدی", lastname: "عوجانی", company: "راتین پردازش" },
    { firstname: "مهدی", lastname: "سواری", company: "پرهام سیستم شهرداد" },
    { firstname: "مهدی", lastname: "امیدی", company: "" },
    { firstname: "مهدی", lastname: "حاجی", company: "اتری" },
    { firstname: "مهدی", lastname: "عربگری", company: "" },
    { firstname: "مهدی", lastname: "حجتی", company: "ایرانسل" },
    { firstname: "مهدی", lastname: "میرزائی", company: "ایرانسل" },
    { firstname: "مهدی", lastname: "مقصودی", company: "دیده بان نت" },
    { firstname: "مهدی", lastname: "حبشی", company: "شبکه بانان پاژ" },
    { firstname: "مهدی", lastname: "سواری", company: "" },
    { firstname: "مهراد", lastname: "فرشچی", company: "آتیه داده پرداز" },
    { firstname: "مهران", lastname: "معين فر", company: "همكاران سيستم" },
    { firstname: "مهران", lastname: "صالحی", company: "رسانگار" },
    { firstname: "مهیار", lastname: "حیاتی", company: "سینداد" },
    { firstname: "مهیار", lastname: "شابداقی", company: "" },
    {
      firstname: "میثم",
      lastname: "شکرآبی",
      company: "زیرساخت امن خدمات تراکنشی(بانک ملت)",
    },
    {
      firstname: "میثم",
      lastname: "قدسی",
      company: "توسعه فناوری ارتباطات پاسارگاد آریان (فناپ تلکام)",
    },
    { firstname: "میلاد", lastname: "راعی", company: "" },
    { firstname: "ناربه", lastname: "آراکیل", company: "Skillz" },
    { firstname: "نرگس", lastname: "گونه", company: "ارتباطات ثابت آوا اروند" },
    { firstname: "نوید", lastname: "نامجو", company: "امن افزار هوپاد" },
    { firstname: "نویسا", lastname: "سدادی", company: "افرانت" },
    { firstname: "نیلوفر", lastname: "کیایی", company: "گروه فناوری پرند" },
    { firstname: "نیما", lastname: "مقصودلو", company: "شبکه گستران گرگان" },
    { firstname: "نیما", lastname: "بخار", company: "دمیل" },
    {
      firstname: "هادی",
      lastname: "همایونفر",
      company: "دهکده مبادله اطلاعات ارژن",
    },
    { firstname: "هلیا", lastname: "بیسادی", company: "" },
    { firstname: "همایون", lastname: "علیرضازاده", company: "" },
    {
      firstname: "هومن",
      lastname: "گران همت",
      company: "ارتباطات سیار ایران (همراه اول)",
    },
    { firstname: "وحید", lastname: "کهساری", company: "ماهان ارتباطات" },
    { firstname: "وحید", lastname: "خوشنود", company: "تک نت" },
    {
      firstname: "وحید",
      lastname: "شهبازیان فرد جهرمی",
      company: "miniRouter",
    },
    { firstname: "یاسین", lastname: "ذاکر", company: "سینداد" },
    { firstname: "سعید", lastname: "محسنی", company: "حلما گستر" },
    { firstname: "رزا", lastname: "خشنودی", company: "آرین تل" },
    { firstname: "علی", lastname: "رضاعلی", company: "فلایتیو" },
    { firstname: "واهاگ", lastname: "گراگوسیان", company: "فلایتیو" },
    { firstname: "مجید", lastname: "سلیمانی", company: "فناوری اطلاعات ماهر" },
    { firstname: "حسن", lastname: "قاسمی", company: "Domil" },
    { firstname: "ایمان", lastname: "کاظمی", company: "Domil" },
    { firstname: "احمدرضا", lastname: "قاسمی", company: "آشا آروین" },
    {
      firstname: "مسعود",
      lastname: "مقصودی",
      company: "توزیع برق استان سمنان",
    },
    { firstname: "مجید", lastname: "کی‌نژاد", company: "اسنپ" },
    { firstname: "محمد", lastname: "جورسرایی", company: "آسیاتک" },
    { firstname: "سید مهران", lastname: "خلدی", company: "هم‌روش" },
    { firstname: "حسین", lastname: "یوسفی", company: "هم‌روش" },
    { firstname: "مسعود", lastname: "پارسانظر", company: "هم‌روش" },
    { firstname: "علی", lastname: "چوپان", company: "هم‌روش" },
    { firstname: "مهسا", lastname: "اکبری", company: "هم‌روش" },
    { firstname: "بابک", lastname: "قدیری", company: "هم‌روش" },
    { firstname: "حسین", lastname: "نکومنش", company: "اسنپ" },
    { firstname: "اسحاق", lastname: "دباغ", company: "شرکت ارتباطات زیرساخت" },
    { firstname: "پیمان", lastname: "بهمن", company: "پرشین تک" },
    { firstname: "علی", lastname: "افشار", company: "پرشین تک" },
  ],
};
