import { IrnogEvent } from "../types";

export const Irnog1: IrnogEvent = {
  title: "اولین",
  time: `خرداد ۱۳۹۶`,
  location: {
    country: "ایران",
    city: "تهران",
    detail: "خیابان شریعتی، سالن کنفرانس پیام سوم ",
    locationLink: "google.com",
  },

  gallery: [
    { image: "/pics/irnog1Gallery/1.jpg" },
    { image: "/pics/irnog1Gallery/2.jpg" },
    { image: "/pics/irnog1Gallery/3.jpg" },
    { image: "/pics/irnog1Gallery/4.jpg" },
    { image: "/pics/irnog1Gallery/5.jpg" },
    { image: "/pics/irnog1Gallery/6.jpg" },
    { image: "/pics/irnog1Gallery/7.jpg" },
    { image: "/pics/irnog1Gallery/8.jpg" },
    { image: "/pics/irnog1Gallery/9.jpg" },
    { image: "/pics/irnog1Gallery/11.jpg" },
    { image: "/pics/irnog1Gallery/12.jpg" },
    { image: "/pics/irnog1Gallery/13.jpg" },
    { image: "/pics/irnog1Gallery/14.jpg" },
    { image: "/pics/irnog1Gallery/15.jpg" },
    { image: "/pics/irnog1Gallery/16.jpg" },
    { image: "/pics/irnog1Gallery/17.jpg" },
    { image: "/pics/irnog1Gallery/18.jpg" },
    { image: "/pics/irnog1Gallery/19.jpg" },
    { image: "/pics/irnog1Gallery/20.jpg" },
    { image: "/pics/irnog1Gallery/21.jpg" },
    { image: "/pics/irnog1Gallery/22.jpg" },
    { image: "/pics/irnog1Gallery/23.jpg" },
    { image: "/pics/irnog1Gallery/25.jpg" },
    { image: "/pics/irnog1Gallery/30.jpg" },
    { image: "/pics/irnog1Gallery/31.jpg" },
    { image: "/pics/irnog1Gallery/35.jpg" },
    { image: "/pics/irnog1Gallery/36.jpg" },
    { image: "/pics/irnog1Gallery/37.jpg" },
    { image: "/pics/irnog1Gallery/38.jpg" },
    { image: "/pics/irnog1Gallery/39.jpg" },
    { image: "/pics/irnog1Gallery/40.jpg" },
    { image: "/pics/irnog1Gallery/41.jpg" },
    { image: "/pics/irnog1Gallery/43.jpg" },
    { image: "/pics/irnog1Gallery/45.jpg" },
    { image: "/pics/irnog1Gallery/46.jpg" },
    { image: "/pics/irnog1Gallery/47.jpg" },
    { image: "/pics/irnog1Gallery/48.jpg" },
    { image: "/pics/irnog1Gallery/49.jpg" },
    { image: "/pics/irnog1Gallery/50.jpg" },
  ],

  Participants: [
    { firstname: "شاهین", lastname: "غرقی", company: "آسیاتک" },
    { firstname: "مرتضی", lastname: "سلطانی", company: "فناوران شبکه سینداد" },
    {
      firstname: "محمدحسین",
      lastname: "فخرایی",
      company: "فناوران شبکه سینداد",
    },
    {
      firstname: "حسین",
      lastname: "اشرف سمنانی",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "مازيار", lastname: "ثنايي آشتياني", company: "آسياتك" },
    { firstname: "مصطفي", lastname: "صدفي", company: "كاوشگرنوين كارآمد" },
    { firstname: "علیرضا", lastname: "کریمی", company: "سپنتا" },
    { firstname: "سید مجید", lastname: "هاشمی", company: "بهاران" },
    { firstname: "ریحانه", lastname: "جاویدی", company: "مخابرات ایران" },
    { firstname: "محمد", lastname: "خطیبی", company: "ایران ناگ" },
    { firstname: "افشین", lastname: "واعظی", company: "رسپینا" },
    { firstname: "عباس", lastname: "قنواتي", company: "راصد" },
    { firstname: "نیلوفر", lastname: "کیایی", company: "رسپینا" },
    {
      firstname: "حسن",
      lastname: "فولادی طرقی",
      company: "داده پردازی رسپینا",
    },
    { firstname: "علیرضا", lastname: "احمدی", company: "انتقال داده ماهان" },
    { firstname: "شهاب", lastname: "وهابزاده", company: "آسياتك" },
    { firstname: "فرشاد", lastname: "منتخبی", company: "Huawei" },
    { firstname: "سید محسن", lastname: "حسینی", company: "رسپینا" },
    { firstname: "پارسا", lastname: "یوسفی", company: "Dabco" },
    { firstname: "پوریا", lastname: "ارقش", company: "Dabco" },
    { firstname: "ابراهیم", lastname: "مجتبایی", company: "رسپینا" },
    {
      firstname: "ابراهیم",
      lastname: "کشی زاده",
      company: "داده پردازی رسپینا",
    },
    { firstname: "اميرحسين", lastname: "ثابت", company: "صفرويك پرداز" },
    { firstname: "علیرضا", lastname: "واحدی", company: "رسپینا" },
    { firstname: "امین", lastname: "محمدی ها", company: "رسپینا" },
    { firstname: "سپهر", lastname: "آشوری", company: "آواگستر" },
    { firstname: "اركان", lastname: "زماني", company: "رهياب تلكام" },
    { firstname: "ماهرخ", lastname: "نعمت اللهی", company: "پارس انلاین" },
    { firstname: "مهدی", lastname: "تقی‌زاده", company: "فیدیلیو" },
    { firstname: "پري", lastname: "جعفرزاده", company: "سازمان صدا و سيما" },
    { firstname: "بهفر", lastname: "هرمزي", company: "ارتباطات پرشيا" },
    { firstname: "محمد", lastname: "یعقوبی", company: "رسپینا" },
    { firstname: "علی", lastname: "باقری", company: "" },
    { firstname: "میثم", lastname: "رحمتیان", company: "راداکو" },
    { firstname: "رضا", lastname: "كلاهدوز", company: "رفاتك" },
    { firstname: "پويا", lastname: "خويشتن دار", company: "" },
    { firstname: "عادل", lastname: "شاهینی", company: "" },
    { firstname: "علیرضا", lastname: "محقق", company: "" },
    { firstname: "مهدی", lastname: "وجدانی زاده", company: "Tic" },
    {
      firstname: "احسان اله",
      lastname: "مدیری",
      company: "صنایع ارتباطی نانو تراشه پارس",
    },
    { firstname: "ياسر", lastname: "سالم", company: "داده پردازي فن آوا" },
    {
      firstname: "اميرمحمدفاتح",
      lastname: "",
      company: "فن آوري اطلاعات سامانه كاوشگر ايده",
    },
    { firstname: "رضا", lastname: "بهروزی", company: "مبین نت" },
    { firstname: "حامد", lastname: "مالکی", company: "آسیاتک" },
    { firstname: "لیلا", lastname: "آقایی میبدی", company: "ارتباطات زیرساخت" },
    { firstname: "امین", lastname: "ملک قاسمی", company: "نخل نت" },
    {
      firstname: "سید علیرضا",
      lastname: "میراحمدی",
      company: "داده پردازی رسپینا",
    },
    { firstname: "سید صالح", lastname: "میران", company: "داده پردازی رسپینا" },
    { firstname: "مسعود", lastname: "خلیل نژاد", company: "آسیاتک" },
    { firstname: "مجید", lastname: "کرانی", company: "" },
    { firstname: "علی", lastname: "نیکنام", company: "گاز استان فارس" },
    { firstname: "کوروش", lastname: "تفرشی", company: "داده پردازی رسپینا" },
    { firstname: "مجید", lastname: "عیسی لو", company: "میزبان داده پاسارگاد" },
    { firstname: "جواد", lastname: "الیاسی", company: "مبین نت" },
    {
      firstname: "محمد صادق",
      lastname: "عطار",
      company: "ارتباطات ثابت پارسیان",
    },
    { firstname: "نجمه", lastname: "آزادیان", company: "گسترش ارتباطات مبنا" },
    { firstname: "تارا", lastname: "بجنوردي", company: "آسياتك" },
    { firstname: "علی", lastname: "سروش", company: "داده پردازی رسپینا" },
    { firstname: "امید", lastname: "کوثری", company: "شبدیز" },
    {
      firstname: "امیر",
      lastname: "بهروان",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "پیمان", lastname: "بهمن", company: "صندوق نفت" },
    { firstname: "شهرزاد", lastname: "نورزاد", company: "شاتل" },
    {
      firstname: "روژیا",
      lastname: "خوردبین",
      company: "شرکت ارتباطات زیرساخت",
    },
    { firstname: "مجتبی", lastname: "منیعی", company: "تک نت" },
    {
      firstname: "زهرا",
      lastname: "زندیه شیرازی",
      company: "شرکت ارتباطات زیر ساخت",
    },
    { firstname: "بهشاد", lastname: "رضایی", company: "تک نت" },
    { firstname: "بهنام", lastname: "نامور", company: "گروه پیشگامان هرمزگان" },
    { firstname: "محمد", lastname: "محمدی", company: "ماریزرایانه" },
    { firstname: "وحید", lastname: "واشقانی فراهانی", company: "" },
    { firstname: "ابراهیم", lastname: "نصرآبادی", company: "" },
    { firstname: "پیمان", lastname: "پورحکاک", company: "رایان تک" },
    { firstname: "امیر", lastname: "سهیلی فر", company: "مروا سیستم" },
    {
      firstname: "صبا",
      lastname: "سرائیان",
      company: "داتیس آرین قشم (داتین)",
    },
    { firstname: "جعفر", lastname: "بخشی فر", company: "آسیاتک" },
    { firstname: "مصطفی", lastname: "نیکزاد", company: "شاتل" },
    { firstname: "بهنام", lastname: "یزدانی", company: "آسیاتک" },
    {
      firstname: "نیما",
      lastname: "یگانه",
      company: "شاتل (آریا رسانه تدیبر)",
    },
    {
      firstname: "شهروز",
      lastname: "شکوه زنگنه",
      company: "گسترش ارتباطات مبنا",
    },
    {
      firstname: "محسن",
      lastname: "حسینی مقدم",
      company: "شاتل (آریا رسانه تدیبر)",
    },
    { firstname: "منصوره", lastname: "عباسی", company: "مخابرات ایران" },
    { firstname: "محسن", lastname: "صداقت", company: "حلما گستر خاورمیانه" },
    {
      firstname: "علیرضا",
      lastname: "دشت پیما",
      company: "حلما گستر خاورمیانه",
    },
    { firstname: "امیر", lastname: "آخوندی اصل", company: "آریا وید رایان" },
    { firstname: "حمید", lastname: "صفری", company: "افرانت" },
    { firstname: "محمدمظفری", lastname: "", company: "گرین وب" },
    { firstname: "علی", lastname: "براداران", company: "آسیاتک" },
    { firstname: "مرتضی", lastname: "صمدیان", company: "نقش اول کیفیت" },
    { firstname: "صادق", lastname: "مهبدرید", company: "نقش اول کیفیت" },
    { firstname: "مهدیه", lastname: "زاهدی دیزجی", company: "مخابرات ایران" },
    { firstname: "فرحناز", lastname: "کرمی", company: "شرکت مخابرات ایران" },
    { firstname: "احسان", lastname: "بهبهانی", company: "لایزر" },
    { firstname: "وحید", lastname: "مرصع فر", company: "مخابرات ایران" },
    { firstname: "علیرضا", lastname: "نوروزی صفا", company: "لایزر" },
    { firstname: "امین", lastname: "بهبهانی", company: "سوشیانت فراداده" },
    { firstname: "سید مسعود", lastname: "طبیب", company: "شرکت مخابرات ایران" },
    { firstname: "مهراد", lastname: "فرشچی", company: "صفر و یک پرداز" },
    { firstname: "حسین", lastname: "دیندوست", company: "مبین نت" },
    { firstname: "شاهین", lastname: "کاظمی", company: "صفرویک پرداز" },
    { firstname: "محمدعلی", lastname: "عبدی", company: "مبین نت" },
    { firstname: "مهدی", lastname: "رباط جزی", company: "مبین نت" },
  ],
};
