import { IrnogEvent } from "../types";

export const Irnog6: IrnogEvent = {
  title: "ششمین",
  time: `پنجشنبه - 14 تیر ماه 1403`,
  location: {
    country: "ایران",
    city: "شیراز",
    detail: "مخابرات ایران منطقه فارس",
    locationLink:
      "https://www.google.com/maps/place/29%C2%B038'00.7%22N+52%C2%B030'24.0%22E/@29.633523,52.506654,17z/data=!3m1!4b1!4m4!3m3!8m2!3d29.633523!4d52.506654?entry=ttu",
  },
  irnogAgenda: [
    {
      presenter: "میلاد افشاری",
      presentationTitle: `
         افتتاحیه
      -IRNOG Community Updates
   
      `,
      presentationLink: "-",
    },
    {
      presenter: "مخابرات ایران، رازمان، لیموهاست",
      presentationTitle: "سخنرانی حامیان پلاتینیوم رویداد",
      presentationLink: "-",
    },
    {
      presenter: "علیرضا کریمی",
      presentationTitle: "AWS Networking",
      presentationLink: "-",
    },
    {
      presenter: "سیدپوریا موسوی زاده تهرانی",
      presentationTitle: "TCP BBR",
      presentationLink: "-",
    },
    {
      presenter: "احسان قاضی زاده",
      presentationTitle:
        "TCP Congestion Avoidance (A Modern Solution to an Old Problem)",
      presentationLink: "-",
    },
    {
      presenter: "RIPE NCC Representative",
      presentationTitle: "RIPE Atlas",
      presentationLink: "-",
    },
    {
      presenter: "بیمان لاری",
      presentationTitle: "Network Automation with Artificial Intelligence",
      presentationLink: "-",
    },
    {
      presenter: "Sara Alamin (Packet Clearing House)",
      presentationTitle: "A Day in PCH's Anycast Network",
      presentationLink: "-",
    },
    {
      presenter: "محمدرضا تجاریاشی",
      presentationTitle: "Deep Dive in Kubernetes Network & Communication",
      presentationLink: "-",
    },
    {
      presenter: "على رضاعلى",
      presentationTitle: "BGP Anycast",
      presentationLink: "-",
    },
    {
      presenter: "سینا سلطانی",
      presentationTitle: "Introduction to Zero Trust Architecture",
      presentationLink: "-",
    },
    {
      presenter: "شهاب وهاب زاده",
      presentationTitle: "اختتامیه",
      presentationLink: "-",
    },
  ],
  sponsers: {
    platinumSponsors: [
      {
        logo: "/logo/sponsers/irnog6/tci.svg",
        link: "https://www.tci.ir/",
        name: "مخابرات",
      },
      {
        logo: "/logo/sponsers/irnog6/razhman.png",
        link: "-  ",
        name: "razhman",
      },
      {
        logo: "/logo/sponsers/irnog6/limoHost.svg",
        link: "https://limoo.host/",
        name: "limo Host",
      },
    ],
  },
  Participants: [
    {
      firstname: "میلاد",
      lastname: "افشاری",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "آریا",
      lastname: "جهانگیری فر",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "محمد",
      lastname: "خطیبی",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "مرتضی",
      lastname: "سلطانی",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "سعید",
      lastname: "سوزنگر",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "وحید",
      lastname: "شهبازیان",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "ابراهیم",
      lastname: "کشی‌زاده",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "امید",
      lastname: "کوثری",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "واهاگ",
      lastname: "گراگوسیان",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "سیدپوریا",
      lastname: "موسوی‌زاده تهرانی",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "شهاب",
      lastname: "وهابزاده",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "پارسا",
      lastname: "یوسفی",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    { firstname: "شایان", lastname: "خیرآبادی", company: "" },
    { firstname: "سید عرفان", lastname: "موسوی", company: "پارس سازان" },
    { firstname: "رضا", lastname: "فرمل", company: "" },
    { firstname: "حسین", lastname: "ابراهیمی", company: "فناوربنیان ثریا" },
    { firstname: "مجید", lastname: "سلیمانیان", company: "فناوربنیان ثریا" },
    { firstname: "علیرضا", lastname: "زاهدی", company: "اریاسرور" },
    { firstname: "حسن", lastname: "مباشری", company: "" },
    {
      firstname: "علیرضا",
      lastname: "نعمت الهی",
      company: "ارتباطات فرآموز کیان مهر (فرکیان تک)",
    },
    { firstname: "علی", lastname: "کرمی", company: "ندارم" },
    {
      firstname: "مجتبی",
      lastname: "صلاحی کجور",
      company: "موج گویای مازندران",
    },
    { firstname: "سیدخلیل", lastname: "موسوی", company: "" },
    { firstname: "حسین", lastname: "کسائیان", company: "" },
    { firstname: "فرزاد", lastname: "کنعانی", company: "همراه اول" },
    { firstname: "سعید", lastname: "جنابی", company: "همراه اول" },
    { firstname: "سبحان", lastname: "صفرپور", company: "" },
    { firstname: "زهرا", lastname: "شمس", company: "" },
    { firstname: "علیرضا", lastname: "زارع", company: "" },
    { firstname: "حمید رضا", lastname: "رنجبر", company: "" },
    { firstname: "پوریا", lastname: "هژبریان", company: "" },
    {
      firstname: "ایمان",
      lastname: "فرهی",
      company: "ارتباطات فرآموز کیان مهر (فرکیان تک)",
    },
    { firstname: "احسان", lastname: "سهامی", company: "" },
    { firstname: "محمد", lastname: "چرخ انداز", company: "عرفان نت" },
    { firstname: "مجید", lastname: "جعفری پناه", company: "رایان پروژه" },
    { firstname: "علیرضا", lastname: "موسوی", company: "" },
    { firstname: "Amirhosein", lastname: "Balaghi", company: "" },
    {
      firstname: "محمدرضا",
      lastname: "خیّر",
      company: "سازمان فناوری اطلاعات و ارتباطات شهرداری شیراز",
    },
    { firstname: "آرش", lastname: "پزندی", company: "شبکه گستر کوروش" },
    { firstname: "مجید", lastname: "اعتمادی", company: "نانو پردازش رباتیک" },
    { firstname: "Mehdi", lastname: "Bazrafkan", company: "" },
    { firstname: "امید", lastname: "ناظم", company: "پایا کنترل پاسارگاد" },
    { firstname: "یاسر", lastname: "ا‌ورنگی", company: "هدیش نت فارس" },
    { firstname: "مهرزاد", lastname: "مقدس", company: "" },
    {
      firstname: "طه",
      lastname: "شمس الدین",
      company: "راژمان الگوریتم هوپاد",
    },
    { firstname: "مریم", lastname: "ثنایی", company: "" },
    { firstname: "محمدرضا", lastname: "سیفی", company: "هم‌روش" },
    { firstname: "مریم", lastname: "آل طه", company: "پرداخت الکترونیک سامان" },
    {
      firstname: "مهدی",
      lastname: "سیاهی",
      company: "مخابرات ایران منطقه فارس",
    },
    {
      firstname: "کمال",
      lastname: "کمایی",
      company: "شرکت گروه فناوری اطلاعات مبنا گسترش تاریانا (سهامی خاص)",
    },
    {
      firstname: "پدرام",
      lastname: "شریفی نسب",
      company: "ماهان ارتباط خلیج فارس",
    },
    {
      firstname: "فرشید",
      lastname: "یزدان شناسیان",
      company: "ماهان ارتباط خلیج فارس",
    },
    { firstname: "سیدحمیدرضا", lastname: "حسینی", company: "" },
    { firstname: "احمدرضا", lastname: "حسینی", company: "" },
    {
      firstname: "فرخ",
      lastname: "نظرپورسروک",
      company: "شرکت مخابرات استان فارس",
    },
    { firstname: "زهرا", lastname: "هوشیار", company: "" },
    { firstname: "صبا", lastname: "ارشدی", company: "ابر دراک" },
    { firstname: "احسان", lastname: "زائری", company: "" },
    { firstname: "سیداحسان", lastname: "حسینی", company: "" },
    { firstname: "علیرضا", lastname: "دهقانیان", company: "" },
    {
      firstname: "حمید",
      lastname: "لطفی پور جهرمی",
      company: "راژمان الگوریتم هوپاد",
    },
    { firstname: "پدرام", lastname: "حسینی", company: "راژمان الگوریتم هوپاد" },
    {
      firstname: "محمد",
      lastname: "شرکت معصوم",
      company: "راژمان الگوریتم هوپاد",
    },
    {
      firstname: "معین",
      lastname: "ایزدی پور",
      company: "راژمان الگوریتم هوپاد",
    },
    { firstname: "جهانگیر", lastname: "کریمی", company: "" },
    {
      firstname: "Mohammad",
      lastname: "Hasan pour",
      company: "رامونا اعتماد ایرانیان",
    },
    { firstname: "حسین", lastname: "کمالی", company: "پرگاس" },
    { firstname: "امیر", lastname: "عسکری", company: "کارخانه نوآوری شیراز" },
    { firstname: "امیرحسین", lastname: "تابش", company: "" },
    { firstname: "امیر محمد", lastname: "فاتح", company: "ابر ایران" },
    { firstname: "علیرضا", lastname: "جاوید", company: "" },
    { firstname: "فریماه", lastname: "جهان پور", company: "لیموهاست" },
    { firstname: "امیرحسین", lastname: "اسکندری", company: "رایان شبکه" },
    { firstname: "محمد", lastname: "زاجری", company: "ایرانسل" },
    { firstname: "محمد مهدی", lastname: "انصاری", company: "" },
    { firstname: "پرهام", lastname: "زردشتی", company: "هم روش" },
    { firstname: "حسین", lastname: "محمدی", company: "همروش" },
    { firstname: "سینا", lastname: "راد", company: "هم‌روش" },
    { firstname: "علیرضا", lastname: "بانشی", company: "همروش" },
    { firstname: "سجاد", lastname: "واعظی", company: "" },
    { firstname: "آزیتا", lastname: "عبداللهی", company: "" },
    { firstname: "مسیح", lastname: "ساده", company: "ابر آینده ایرانیان" },
    {
      firstname: "سجاد",
      lastname: "زینال پور",
      company: "مهرگان دانش پژوه (سپنتا)",
    },
    { firstname: "احسان", lastname: "قاضی‌زاده", company: "کافه بازار" },
    { firstname: "سهیر", lastname: "صالحی", company: "" },
    { firstname: "ایمان", lastname: "عارفخانی", company: "امنش" },
    { firstname: "مهدی", lastname: "وارسته", company: "امنش" },
    { firstname: "علیرضا", lastname: "رمضان زاده", company: "لیموهاست" },
    { firstname: "داود", lastname: "منتظری", company: "مبین هاست" },
    { firstname: "علی", lastname: "رضاعلی", company: "تلوبیون" },
    { firstname: "سحر", lastname: "یوسفی", company: "" },
    { firstname: "عمید", lastname: "کاظمی", company: "پارین سرور" },
    { firstname: "رضا", lastname: "مومن", company: "" },
    { firstname: "محمد رضا", lastname: "مستمع", company: "راسپینا نت پارس" },
    { firstname: "سید امیرعلی", lastname: "برقعی", company: "امن افزار هوپاد" },
    { firstname: "سعید", lastname: "بیضائی نژاد", company: "" },
    { firstname: "محمد", lastname: "صائب", company: "HUAWEI" },
    { firstname: "مهدی", lastname: "حبشی", company: "آسیاتک" },
    { firstname: "نوید", lastname: "نامجو", company: "امن افزار هوپاد" },
    { firstname: "حامد", lastname: "کارگرزاده", company: "رسپینا" },
    { firstname: "مهرداد", lastname: "موسوی", company: "سازمان فاوا" },
    { firstname: "Hamed", lastname: "Khademzadeh", company: "TA" },
    { firstname: "Mahdi", lastname: "Farshchi", company: "QBIC" },
    { firstname: "راحله", lastname: "لنگری", company: "مخابرات" },
    { firstname: "بهروز", lastname: "غفوریان", company: "بهسا" },
    { firstname: "علی", lastname: "قدیمی مقدم", company: "وب داده" },
    { firstname: "محمدرضا", lastname: "جوادی محب", company: "وب داده" },
    { firstname: "وحید", lastname: "عباسی", company: "" },
    { firstname: "علی", lastname: "رحمانی", company: "هلدینگ آی کن" },
    { firstname: "محمدعلی", lastname: "رنجبر", company: "" },
    { firstname: "سینا", lastname: "فرنگی", company: "لیموهاست" },
    { firstname: "دارا", lastname: "جوکار", company: "" },
    { firstname: "مریم", lastname: "صابری", company: "شرکت مخابرات" },
    { firstname: "محمدحسین", lastname: "احمدی لاری", company: "" },
    { firstname: "حسین", lastname: "هدایتی", company: "" },
    {
      firstname: "سها",
      lastname: "کاسمی",
      company: "شرکت مخابرات ایران منطقه فارس",
    },
    { firstname: "فروغ", lastname: "آزادگان جهرمی", company: "" },
    { firstname: "حسین", lastname: "حیاتی منفرد", company: "آزاد" },
    {
      firstname: "احمدعلی",
      lastname: "افشاری نژاد",
      company: "اداره کل آموزش و پرورش فارس",
    },
    { firstname: "محمد هادی", lastname: "آزاددل", company: "" },
    {
      firstname: "معصومه",
      lastname: "کاراندیش",
      company: "ویستا شبکه فن آوران پارس",
    },
    {
      firstname: "علی",
      lastname: "نکونام",
      company: "ویستا شبکه فن اوران پارس",
    },
    { firstname: "دریا", lastname: "بهرامی", company: "آذرآنلاین" },
    { firstname: "پویا", lastname: "شورانگیز حقیقی", company: "ابر دراک" },
    { firstname: "عرفان", lastname: "خوش رضا", company: "ابر دراک" },
    { firstname: "رضا", lastname: "خوارزمی نیا", company: "رایا ابردراک پارس" },
    { firstname: "محمود", lastname: "طیبی", company: "" },
    { firstname: "سروش", lastname: "سلطانی", company: "ابر دراک" },
    { firstname: "سارا", lastname: "موسوی راد", company: "ابر دراک" },
    { firstname: "سینا", lastname: "سلطانی", company: "ابر دراک" },
    { firstname: "رامتین", lastname: "رحمانی نژاد اصیل", company: "" },
    { firstname: "آرین", lastname: "کبیر", company: "" },
    { firstname: "محمدرضا", lastname: "باغ بهاری", company: "" },
    { firstname: "امیرمسعود", lastname: "شاکر", company: "فلایتیو" },
    {
      firstname: "سید محسن",
      lastname: "موسوی نژاد",
      company: "گسترش ارتباطات صبا",
    },
    { firstname: "میثم", lastname: "فلاح زاده", company: "" },
    { firstname: "رحیم", lastname: "عباس زاده", company: "جهان سبز مهر" },
    { firstname: "محمدرضا", lastname: "حزنیان", company: "همراه اول" },
    { firstname: "محمدحسین", lastname: "استوار", company: "" },
    { firstname: "سیدمحمدحسین", lastname: "سلالت", company: "مخابرات" },
    {
      firstname: "لیلا",
      lastname: "خلیلی شبلوئی",
      company: "دانشگاه علوم پزشکی",
    },
    { firstname: "احسان", lastname: "زینلیان زاده", company: "مبین نت" },
    { firstname: "رضا", lastname: "صلاحی احمد ابادی", company: "رایان تک" },
    { firstname: "حامد", lastname: "آذری", company: "مخابرات" },
    { firstname: "عليرضا", lastname: "قهرود", company: "كملن امن دياكو" },
    { firstname: "Mr", lastname: "Adel", company: "" },
    { firstname: "علیرضا", lastname: "احمدی فر", company: "" },
    {
      firstname: "مجتبی",
      lastname: "سواری",
      company: "مبنا گسترش سیستم آروین",
    },
    {
      firstname: "محی الدین",
      lastname: "قاسم زاده",
      company: "دام و طیور فارس",
    },
    { firstname: "امیرمهدی", lastname: "زیتون", company: "" },
    { firstname: "شروین", lastname: "احمدی", company: "" },
    { firstname: "سیدیوسف", lastname: "موسوی", company: "نوآوارن شبکه بنیان" },
    { firstname: "امیر", lastname: "عزیزی", company: "" },
    { firstname: "Mohammad", lastname: "Razavi", company: "" },
    { firstname: "رضا", lastname: "واحدی", company: "پیشگامان" },
    { firstname: "امیرعباس", lastname: "مقیمی", company: "" },
    { firstname: "مهدی", lastname: "سواری", company: "مبنا گسترش سیستم آروین" },
    { firstname: "محمدعلی", lastname: "یعقوبی", company: "" },
    { firstname: "نسرین", lastname: "غیاثی", company: "مخابرات" },
    { firstname: "محمدرضا", lastname: "حسن زاده", company: "" },
    { firstname: "امیر", lastname: "حیدری منفرد", company: "دانشگاه آزاد" },
    { firstname: "مصطفی", lastname: "چکامه گوی مطلق", company: "واژه" },
    { firstname: "منصور", lastname: "مرزبان", company: "" },
    { firstname: "اسماعیل", lastname: "یزدانی", company: "ایریسا" },
    { firstname: "علی", lastname: "متاله", company: "مخابرات منطقه فارس" },
    {
      firstname: "عبدالعظیم",
      lastname: "رحیم پور",
      company: "میزبانی ابر وارش",
    },
    { firstname: "حسن", lastname: "بهمنی", company: "" },
    { firstname: "Adel", lastname: "Shahini", company: "N/A" },
    { firstname: "حدیثه", lastname: "غفوری", company: "" },
    { firstname: "امیرحسین", lastname: "شیرازی", company: "" },
    { firstname: "پارسا", lastname: "ناظر", company: "byeto" },
    { firstname: "سیدمحمدحسین", lastname: "طباطبائی فرد", company: "" },
    {
      firstname: "ارشاد",
      lastname: "مختاری",
      company: "فناوری رایانه هوشمند هیراد",
    },
    {
      firstname: "ایمان",
      lastname: "بابایی پور",
      company: "پارس مهر ارتباطات",
    },
    { firstname: "سید شاهین", lastname: "حسینی", company: "" },
    {
      firstname: "امیر",
      lastname: "اکبری زاده",
      company: "گسترش ارتباطات صبا",
    },
    { firstname: "زهرا", lastname: "همتی", company: "آریاسرور" },
    {
      firstname: "ژیلا",
      lastname: "نجف زاده اسکویی",
      company: "ارتباطات زیرساخت",
    },
    { firstname: "زهرا", lastname: "اسفندیاری بیات", company: "" },
    { firstname: "سینا", lastname: "سعدین خرم", company: "" },
    {
      firstname: "نیلوفر",
      lastname: "حسینی",
      company: "مجتمع آموزشی امام رضا",
    },
    { firstname: "مهدی", lastname: "بوشهری", company: "فراهوش دنا" },
    { firstname: "رسا", lastname: "کمالی", company: "" },
    { firstname: "ایمان", lastname: "کمالی", company: "" },
    { firstname: "محمد", lastname: "بوشهری", company: "فراهوش دنا" },
    {
      firstname: "محمد صابر",
      lastname: "دولت آبادی",
      company: "نظم آوران صنعت و معدن گل‌گهر",
    },
    { firstname: "امید", lastname: "اخگری", company: "آروان کلاد" },
    { firstname: "امیرحسین", lastname: "برخورداری", company: "" },
    { firstname: "فائزه", lastname: "احمدی", company: "" },
    { firstname: "Nazanin", lastname: "Parhizgar", company: "" },
    { firstname: "حسین", lastname: "مهرزاد", company: "نام شرکت" },
    { firstname: "محمدرضا", lastname: "نجارباشی", company: "" },
    { firstname: "علی", lastname: "همدانی", company: "پارس سازان" },
    { firstname: "پارسا", lastname: "شفیعی", company: "" },
    { firstname: "زهرا", lastname: "کشاورز", company: "" },
    { firstname: "زهرا", lastname: "قادریان", company: "" },
    { firstname: "عظیم", lastname: "جاویدی", company: "" },
    {
      firstname: "الهام",
      lastname: "محمودی بابرصاد",
      company: "شبکه طرح مدار ایرانیان",
    },
    { firstname: "سینا", lastname: "قمری", company: "شبکه طرح مدار ایرانیان" },
    {
      firstname: "راضیه",
      lastname: "علی اکبری",
      company: "فناوری ارتباطات پویان",
    },
    { firstname: "زینب", lastname: "گل", company: "فناوری ارتباطات پویان" },
    { firstname: "جاسم", lastname: "صبوری", company: "میزبان داده پردیس" },
    { firstname: "عرشیا", lastname: "خادمی", company: "میزبان داده پردیس" },
    { firstname: "محمد", lastname: "کفاشی", company: "میزبان داده پردیس" },
    { firstname: "محمد مهدی", lastname: "جاوید", company: "" },
    { firstname: "مهدی", lastname: "رفیعی", company: "ستون" },
    { firstname: "زهرا", lastname: "غریب", company: "لیموهاست" },
    { firstname: "جلال", lastname: "مقدم", company: "" },
    { firstname: "سروش", lastname: "کاویانی", company: "لیموهاست" },
    { firstname: "جواد", lastname: "مقدم", company: "" },
    { firstname: "مرتضی", lastname: "شجاعی اصل", company: "لیموهاست" },
    {
      firstname: "بنیامین",
      lastname: "جمالی فرد",
      company: "میزبان داده پردیس",
    },
    { firstname: "سیدرضا", lastname: "سیادت نژاد", company: "" },
    { firstname: "مهدی", lastname: "مقصودی", company: "دیده بان نت" },
    { firstname: "مسعود", lastname: "سلطانی", company: "دیده بان نت" },
    { firstname: "عبدالرسول", lastname: "کمالیان فر", company: "کمال آموز" },
    {
      firstname: "بهنام",
      lastname: "پورجانعلی",
      company: "همکاران نیک اندیش مدیریت تبریز",
    },
    { firstname: "علی", lastname: "زاهدی", company: "دیده بان نت" },
    { firstname: "محمد مهدی", lastname: "بانشی", company: "" },
    { firstname: "مهرداد", lastname: "صادقی", company: "" },
    { firstname: "فاطمه", lastname: "زاهدیان نسب", company: "دارگیز" },
    { firstname: "ابراهیم", lastname: "انصافی", company: "سیب سبز" },
    {
      firstname: "نیما",
      lastname: "سبحانی جو",
      company: "پالایش گاز بیدبلند خلیج فارس",
    },
    { firstname: "شبنم", lastname: "نیکانیک", company: "شرکت مخابرات ایران" },
    { firstname: "حسن", lastname: "فولادی", company: "" },
    { firstname: "حمید", lastname: "یوسفی", company: "" },
    {
      firstname: "حامد",
      lastname: "شفقی",
      company: "MIHAN COMMUNICATION SYSTEMS",
    },
    { firstname: "علی", lastname: "رحیمی", company: "" },
    { firstname: "حمیدرضا", lastname: "رهنما", company: "مالیت" },
    { firstname: "حانیه", lastname: "مروی", company: "هم‌روش" },
    { firstname: "علیرضا", lastname: "قربتی", company: "مهیمن" },
    { firstname: "خدیجه", lastname: "کهنسال", company: "" },
    { firstname: "آریا", lastname: "امامی", company: "" },
    { firstname: "جواد", lastname: "مرادی", company: "دانشگاه شیراز" },
    { firstname: "قاسم", lastname: "باصری", company: "" },
    { firstname: "سید مهران", lastname: "خلدی", company: "هم‌روش" },
    { firstname: "خسرو", lastname: "عظیمی", company: "" },
    { firstname: "امیرمحمد", lastname: "ولی پور", company: "" },
    { firstname: "امین", lastname: "ملک قاسمی", company: "آترین نت" },
    { firstname: "فائزه", lastname: "ادهمی", company: "adnm" },
    { firstname: "محمدمحسن", lastname: "میرزائی", company: "" },
    { firstname: "عباس", lastname: "داورپناه", company: "" },
    { firstname: "مجید", lastname: "صیدی", company: "Kazintercom LLC." },
    {
      firstname: "امیر",
      lastname: "خیاط احسانی",
      company: "رایا ابر دراک پارس",
    },
    { firstname: "گودرز", lastname: "جعفری", company: "" },
    { firstname: "محسن", lastname: "اطیابی", company: "مدیا پرداز سیستم" },
    { firstname: "شایسته", lastname: "رادفر", company: "شرکت نفت" },
    { firstname: "مجتبی", lastname: "منیعی", company: "تک نت" },
    { firstname: "عرفان", lastname: "قوامی نیا", company: "علی بابا" },
    { firstname: "محمد علی", lastname: "خانجانی", company: "IRPOWER" },
    { firstname: "علی", lastname: "شمس آبادی", company: "IRPOWER" },
    { firstname: "علی", lastname: "پرستار", company: "IRPOWER" },
    {
      firstname: "مهدیه",
      lastname: "زاهدی دیزجی",
      company: "شرکت مخابرات ایران",
    },
    { firstname: "سیدمحمد", lastname: "منصوری", company: "" },
    { firstname: "حمیدرضا", lastname: "انصافی", company: "گسترش فناوری نوین" },
    { firstname: "محسن", lastname: "محمدی", company: "ایرانیکاسرور" },
    { firstname: "محمد", lastname: "اکبری", company: "مرکز داده ابر باران" },
    { firstname: "صادق", lastname: "احمدی نژاد گشوییه", company: "" },
    { firstname: "فاطمه", lastname: "مظاهریان", company: "" },
    { firstname: "مهدی", lastname: "خانلری", company: "افرانت" },
    { firstname: "علی", lastname: "نیکنام", company: "لوتوس" },
    {
      firstname: "ونوس",
      lastname: "صابرزاده",
      company: "دانشگاه علوم پزشکی شیراز",
    },
    { firstname: "علی", lastname: "محمدی", company: "" },
    { firstname: "محمد", lastname: "نخجیری", company: "" },
    { firstname: "امیرحسین", lastname: "فکورپور", company: "دانشگاه شیراز" },
    { firstname: "محسن", lastname: "آقایی", company: "فناوری ارتباطات پویان" },
    { firstname: "سروش", lastname: "زندی", company: "فناوری ارتباطات پویان" },
    { firstname: "فربد", lastname: "صولت", company: "" },
    { firstname: "سارا", lastname: "همایونی", company: "همایون شبکه رامند" },
    { firstname: "کیان", lastname: "دادور", company: "آیویوید" },
    { firstname: "مجید", lastname: "رجایی", company: "" },
    { firstname: "مریم", lastname: "زارعیان جهرمی", company: "مینی روتر" },
    {
      firstname: "سید عباس",
      lastname: "حسینی",
      company: "داده گستر سینا شیراز",
    },
    { firstname: "آیسان", lastname: "نظرمحمدی", company: "ایسنا" },
    { firstname: "حمید", lastname: "حسن زاده", company: "" },
    { firstname: "پیمان", lastname: "لاری", company: "خانه لینوکس شیراز" },
    { firstname: "مهرداد", lastname: "فرزام فر", company: "آریا سرور" },
    {
      firstname: "پیمان",
      lastname: "پیمان نژاد",
      company: "دانشگاه علوم پزشکی شیراز",
    },
    { firstname: "علیرضا", lastname: "پورعابدین", company: "پارس‌پک" },
    { firstname: "سید رسول", lastname: "رضوی", company: "" },
    {
      firstname: "محمدجواد",
      lastname: "عرشیان",
      company: "خبرگزاری دانشجویان ایران (ایسنا)",
    },
    { firstname: "زاهدی", lastname: "خدیجه", company: "شرکت مخابرات ایران" },
    { firstname: "علیرضا", lastname: "انصافی", company: "" },
    { firstname: "محمد جواد", lastname: "آریافر", company: "ابر دراک" },
    { firstname: "آرین", lastname: "رحیمی", company: "" },
    { firstname: "محمد رحیم", lastname: "کریمی فرد", company: "" },
    {
      firstname: "پوریا",
      lastname: "کشاورز مویدی",
      company: "بیمارستان دکتر امامی",
    },
    { firstname: "parham", lastname: "bagheri", company: "ایکاد فناوری ارکان" },
    { firstname: "mehdi", lastname: "rajabzadeh", company: "arkan" },
    {
      firstname: "امیرحسین",
      lastname: "زارعیان",
      company: "ایکاد فناوری آرکان",
    },
    { firstname: "احسان", lastname: "بهمنی", company: "" },
    { firstname: "حسین", lastname: "زاهدی", company: "آریاسرور" },
    {
      firstname: "مجید",
      lastname: "مقصودفر",
      company: "دانشگاه علوم پزشکی تبریز",
    },
    { firstname: "محسن", lastname: "پهلوان‌زاده", company: "" },
    { firstname: "شهریار", lastname: "بیضائی نژاد", company: "Wi4i.com" },
    { firstname: "امیررضا", lastname: "ترویج", company: "کافه بازار" },
    { firstname: "پوریا", lastname: "تعبدی", company: "ندا گستر صبا (صبانت)" },
    { firstname: "مجید", lastname: "گنجی", company: "شرکت مخابرات ایران" },
    { firstname: "آرمان", lastname: "ضیایی پور", company: "" },
    { firstname: "حسین", lastname: "ابراهیمی", company: "" },
    { firstname: "علی", lastname: "داوری", company: "تولید نیروی برق شاهرود" },
    { firstname: "کوروش", lastname: "نوروزی", company: "" },
    { firstname: "فتاح", lastname: "شاکری حقیقی", company: "" },
    { firstname: "محمد", lastname: "ضربعلی زاده", company: "مخابرات" },
    { firstname: "سید مهدی", lastname: "خلیفه لو", company: "هم روش" },
    { firstname: "علی", lastname: "رضائ", company: "زاگرس هاست" },
    { firstname: "مصطفی", lastname: "خوشنود", company: "امن افزار هوپاد" },
    { firstname: "محمدحسین", lastname: "ایزدی", company: "وب داده" },
    { firstname: "متین", lastname: "بلوچستانی", company: "وب داده" },
    { firstname: "سید محمد", lastname: "فخرایی", company: "" },
    { firstname: "فواد", lastname: "بهزادی", company: "آروان کلاد" },
    { firstname: "ریحانه", lastname: "جاویدی", company: "شرکت مخابرات ایران" },
    { firstname: "شهاب", lastname: "سیدان", company: "ابر دراک" },
    {
      firstname: "عبدالمجید",
      lastname: "امامی",
      company: "شرکت مخابرات ایران",
    },
    {
      firstname: "پیام",
      lastname: "صمدیان",
      company: "فناوران اطلاعات ابر باران",
    },
    { firstname: "مرتضی", lastname: "اعلم الهدی", company: "ایفاسرام" },
    { firstname: "مهدی", lastname: "نوزادی", company: "فرا ارتباط گستر پویا" },
    { firstname: "سعید", lastname: "یاوری", company: "" },
    { firstname: "محمد", lastname: "مظفری", company: "گرین وب" },
    { firstname: "محمدحسن", lastname: "جعفرزاده", company: "داده پردازی مبین" },
    { firstname: "احسان", lastname: "مومنی", company: "داده ورزی سداد" },
    {
      firstname: "علی",
      lastname: "عابدی",
      company: "فناوران اطلاعات ابر باران",
    },
    { firstname: "صادق", lastname: "نجاتی زاده", company: "" },
    { firstname: "علیرضا", lastname: "کریمی", company: "" },
    { firstname: "ابوالفضل", lastname: "حسینی", company: "نوین ارتباط" },
    { firstname: "محسن", lastname: "کربلائی امینی", company: "نئور" },
    { firstname: "آرین", lastname: "اردشیری", company: "پرس‌لاین" },
    { firstname: "امیرحسین", lastname: "فروزانی", company: "ابر دراک" },
    { firstname: "کیانوش", lastname: "عشایری زاده", company: "اسنپ" },
    {
      firstname: "امید",
      lastname: "حکایتی",
      company: "گروه توسعه نابغه ها (geniuses.group)",
    },
    { firstname: "سعید", lastname: "آگاه", company: "مرکزداده امین" },
    { firstname: "محسن", lastname: "طهماسبی", company: "" },
    { firstname: "صابر", lastname: "مسگری", company: "ابرآروان" },
    { firstname: "Jalal", lastname: "Mazaheri", company: "Netafraz iranian" },
    { firstname: "محمد", lastname: "اقبال", company: "" },
  ],
};
