import { IrnogEvent } from "../types";

export const Irnog5: IrnogEvent = {
  title: "پنجمین",
  time: `پنجشنبه - 28 دی ماه 1402`,
  location: {
    country: "ایران",
    city: "تهران",
    detail:
      "تهران، خیابان شیخ بهایی جنوبی، شهرک والفجر، خیابان ایرانشناسی، خیابان نهم، پلاک 6 ، مرکز همایشهای سازمان مدیریت صنعتی ​",
    locationLink:
      "https://www.google.com/maps/place/Industrial+Management+Institute+Conference+Center/@35.7465455,51.3909183,17.82z/data=!4m6!3m5!1s0x3f8e06e06685a833:0x643c1896ac35058c!8m2!3d35.7466919!4d51.3906128!16s%2Fg%2F11b5pjzyc2?entry=ttu",
  },
  irnogAgenda: [
    {
      presenter: "میلاد افشاری",
      presentationTitle: "IRNOC Community Updates",
      presentationLink: "https://www.aparat.com/v/b5264x4",
    },
    {
      presenter: "سخنرانی حامیان مالی پلاتینیوم - ابر‌دراک",
      presentationTitle: "سخنرانی حامیان مالی پلاتینیوم - ابر‌دراک",
      presentationLink: "https://www.aparat.com/v/x270cc8",
    },
    {
      presenter: "سخنرانی حامیان مالی پلاتینیوم - آروان کلاد",
      presentationTitle: "سخنرانی حامیان مالی پلاتینیوم - آروان کلاد",
      presentationLink: "https://www.aparat.com/v/c85a8e8",
    },
    {
      presenter: "سخنرانی حامیان مالی پلاتینیوم - همروش	",
      presentationTitle: "سخنرانی حامیان مالی پلاتینیوم - همروش	",
      presentationLink: "https://www.aparat.com/v/EWvVP",
    },
    {
      presenter: "احسان قاضی زاده",
      presentationTitle: "BGP Automation and Monitoring",
      presentationLink: "https://www.aparat.com/v/d47u2si",
    },
    {
      presenter: "مهربان خلدی",
      presentationTitle: "Traffic Classification Using eBPF",
      presentationLink: "https://www.aparat.com/v/n31t590",
    },
    {
      presenter: "آیسان نظرمحمدی",
      presentationTitle: "Benefits of AI in Network Management",
      presentationLink: "https://www.aparat.com/v/opyb3",
    },
    {
      presenter: "Alastair Strachan (RIPE NCC)",
      presentationTitle: "BGP Routing Security (Hijacks vs RPKI)",
      presentationLink: "https://www.aparat.com/v/76hBG",
    },
    {
      presenter: "رضا خانواکبری",
      presentationTitle: "Zero Trust Network and Cloud Security",
      presentationLink: "https://www.aparat.com/v/8C2Ov",
    },
    {
      presenter: "سید پوریا موسوی زاده تهرانی",
      presentationTitle: "Virtualized Network Stack",
      presentationLink: "https://www.aparat.com/v/i07oivw",
    },
    {
      presenter: "ابوالفضل نجفی",
      presentationTitle: "IPv6 Story in MTN Irancell",
      presentationLink: "https://www.aparat.com/v/r82cab9",
    },
    {
      presenter: "احسان حسینی",
      presentationTitle: "Real World Attacks on Service Providers",
      presentationLink: "https://www.aparat.com/v/06rG7",
    },
    {
      presenter: "سینا سلطانی",
      presentationTitle: "https://www.aparat.com/v/u44uo5v",
      presentationLink: "-",
    },
    {
      presenter: "صابر مسگری",
      presentationTitle: "HA in Real World",
      presentationLink: "https://www.aparat.com/v/q6H8S",
    },
    {
      presenter: "پوریا گردزری",
      presentationTitle: "Netdevops CI/CD Pipeline(Test/Verification)",
      presentationLink: "https://www.aparat.com/v/Vh0R3",
    },
    {
      presenter: "آرش حاتمی",
      presentationTitle: "کاتران - توزیع بار در اینترنت امروز",
      presentationLink: "-",
    },
    {
      presenter: "محمد خطبین",
      presentationTitle: "اختتامیه",
      presentationLink: "https://www.aparat.com/v/k726y3x",
    },
  ],
  sponsers: {
    platinumSponsors: [
      {
        logo: "/logo/sponsers/irnog5/derakCloud.png",
        link: "https://derak.cloud/",
        name: "derakCloud",
      },
      {
        logo: "/logo/sponsers/irnog4/hamRavesh.jpg",
        link: "https://hamravesh.com/",
        name: "هم روش",
      },
      {
        logo: "/logo/sponsers/irnog5/avancloud.png",
        link: "https://www.arvancloud.ir/en",
        name: "arvancloud",
      },
    ],
    goldSponsors: [
      {
        logo: "/logo/sponsers/irnog5/mobinHost.png",
        link: "https://www.mobinhost.com/about-us/",
        name: "mobin Host",
      },
    ],
    silverSponsors: [
      {
        logo: "/logo/sponsers/irnog5/mihanWebHost.png",
        link: "https://mihanwebhost.com/",
        name: "Mihan Web Host",
      },
    ],
    ConnectivitySponsors: [
      {
        logo: "/logo/sponsers/irnog5/liveKadeh.png",
        link: "https://livekadeh.com/",
        name: "live kadeh",
      },
      {
        logo: "/logo/sponsers/irnog5/respina.png",
        link: "https://respina.net/?lang=en",
        name: "respina",
      },
    ],
  },

  gallery: [
    { image: "/pics/irnog5Gallery/1.jpg" },
    { image: "/pics/irnog5Gallery/2.jpg" },
    { image: "/pics/irnog5Gallery/3.jpg" },
    { image: "/pics/irnog5Gallery/4.jpg" },
    { image: "/pics/irnog5Gallery/5.jpg" },
    { image: "/pics/irnog5Gallery/6.jpg" },
    { image: "/pics/irnog5Gallery/7.jpg" },
    { image: "/pics/irnog5Gallery/8.jpg" },
    { image: "/pics/irnog5Gallery/9.jpg" },
  ],
  Participants: [
    {
      firstname: "میلاد",
      lastname: "افشاری",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "آریا",
      lastname: "جهانگیری فر",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "محمد",
      lastname: "خطیبی",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "مرتضی",
      lastname: "سلطانی",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "سعید",
      lastname: "سوزنگر",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "وحید",
      lastname: "شهبازیان",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "ابراهیم",
      lastname: "کشی‌زاده",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "امید",
      lastname: "کوثری",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "واهاگ",
      lastname: "گراگوسیان",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "سیدپوریا",
      lastname: "موسوی‌زاده تهرانی",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "شهاب",
      lastname: "وهابزاده",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    {
      firstname: "پارسا",
      lastname: "یوسفی",
      company: "عضو کمیته هماهنگی مرکزی",
    },
    { firstname: "f", lastname: "heidari", company: "" },
    { firstname: "Hamid", lastname: "Naeemabadi", company: "Domil" },
    { firstname: "Amir", lastname: "Soheilifar", company: "مروا هاست" },
    { firstname: "Arman", lastname: "Taheri", company: "Soshyant" },
    { firstname: "بهراد", lastname: "احمدپور", company: "" },
    { firstname: "محمد", lastname: "احمدی", company: "افرانت" },
    {
      firstname: "سپهر",
      lastname: "احمدی",
      company: "تدبیرپردازان ایده های ابری",
    },
    { firstname: "دانیال", lastname: "احمدی", company: "دواپس‌یار" },
    { firstname: "کسری", lastname: "احمدی پشته", company: "" },
    { firstname: "امید", lastname: "اخگری", company: "اسپکسا" },
    { firstname: "علی اکبر", lastname: "اخوان آریج", company: "آروان کلاد" },
    { firstname: "آرین", lastname: "اردشیری", company: "پرس‌لاین" },
    {
      firstname: "امیرمسعود",
      lastname: "اسلامی",
      company: "نقش روز / پیشگامان",
    },
    { firstname: "امید", lastname: "اسماعیل زاده", company: "فنخاب" },
    { firstname: "محمدرضا", lastname: "اصغرنیا روشن", company: "ایرانسل" },
    { firstname: "سید محسن", lastname: "اطیابی", company: "مدیا پرداز سیستم" },
    { firstname: "حامد", lastname: "اعظمی", company: "domil" },
    { firstname: "مرتضی", lastname: "اعلم الهدی", company: "شرکت ایفاسرام" },
    {
      firstname: "حسین",
      lastname: "افروخته گان",
      company: "تجارت الکترونیک نوژن پردازش",
    },
    { firstname: "محمدامیر", lastname: "افشار", company: "شبکیه اصفهان" },
    { firstname: "حمیدرضا", lastname: "افشار", company: "" },
    { firstname: "رضا", lastname: "افقه", company: "ستون" },
    {
      firstname: "محمد",
      lastname: "اکبری",
      company: "فناوران اطلاعات ابر باران",
    },
    {
      firstname: "امیر",
      lastname: "اکبری زاده",
      company: "گسترش ارتباطات صبا",
    },
    { firstname: "مریم", lastname: "الشتری", company: "پیشگامان" },
    {
      firstname: "علی",
      lastname: "الماسی",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "شهروز", lastname: "امیدوار اوغانی", company: "Sapramin" },
    { firstname: "آذین", lastname: "امیدی‌پور", company: "ایرانسل" },
    { firstname: "احمد", lastname: "امیراحمدی", company: "وایراک کلود" },
    { firstname: "محمداحسان", lastname: "اوکلی", company: "زرین‌پال" },
    { firstname: "محمدحسین", lastname: "ایزدی", company: "افرانت" },
    { firstname: "حسین", lastname: "ایزدی", company: "وب داده" },
    { firstname: "احسان", lastname: "ایمانی", company: "کندو دانش" },
    { firstname: "الهه", lastname: "آجرلو", company: "همراه اول" },
    {
      firstname: "محمد",
      lastname: "آجورلو",
      company: "ایده گزین ارتباطات روماک - اسنپ",
    },
    { firstname: "محمد هادی", lastname: "آزاددل", company: "آسا" },
    { firstname: "علی", lastname: "آزادی", company: "ازکی وام" },
    { firstname: "حسین", lastname: "آقانصیر", company: "" },
    { firstname: "محسن", lastname: "آقایی", company: "فناوری ارتباطات پویان" },
    { firstname: "سعید", lastname: "آگاه", company: "مرکزداده امین" },
    { firstname: "سیدمحمدامین", lastname: "آل احمد", company: "" },
    { firstname: "سعید", lastname: "آوخ", company: "" },
    {
      firstname: "ایمان",
      lastname: "بابایی پور",
      company: "پارس مهر ارتباطات",
    },
    { firstname: "محمد", lastname: "باتوانی", company: "اسنپ" },
    { firstname: "رضا", lastname: "بازمانی", company: "چابکان" },
    {
      firstname: "امیرحسین",
      lastname: "باستانی",
      company: "فناوری پیشرفته پارسیان",
    },
    {
      firstname: "منصور",
      lastname: "باغستانی",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "حسین", lastname: "بحری", company: "لایزر" },
    { firstname: "نیما", lastname: "بخار", company: "دمیل" },
    { firstname: "پارسا", lastname: "بختیاری", company: "" },
    { firstname: "نیما", lastname: "برزگر", company: "ویراک" },
    { firstname: "سیدامیرعلی", lastname: "برقعی", company: "امن افزار هوپاد" },
    { firstname: "محمدصالح", lastname: "برهانی", company: "" },
    {
      firstname: "سعید",
      lastname: "بلادی موسوی",
      company: "بهان پردازش ارشان",
    },
    { firstname: "متین", lastname: "بلوچستانی", company: "وب داده" },
    { firstname: "مسعود", lastname: "بنائی", company: "" },
    { firstname: "علیرضا", lastname: "بهادری زاده", company: "" },
    {
      firstname: "سید مهدی",
      lastname: "بهجتی اصل",
      company: "سامانه های نوآوری ارتباطات سینا",
    },
    { firstname: "مهدی", lastname: "بهرامی", company: "" },
    { firstname: "رضا", lastname: "بهروزی", company: "هاست ایران" },
    { firstname: "فواد", lastname: "بهزادی", company: "آروان کلاد" },
    { firstname: "بهرام", lastname: "بهزادی", company: "" },
    { firstname: "احمد", lastname: "بیات", company: "" },
    { firstname: "محمود", lastname: "بیاتی", company: "" },
    {
      firstname: "دانیال",
      lastname: "بیاری",
      company: "تجارت الکترونیک نوژن پردازش",
    },
    {
      firstname: "فروتن",
      lastname: "بیانی",
      company: "نواندیشان ارتباط امن رسیس",
    },
    { firstname: "حامد", lastname: "بیدی", company: "کارزار" },
    { firstname: "آرش", lastname: "پارساپور", company: "دیجیاتو" },
    { firstname: "میلاد", lastname: "پاکزاد", company: "ویراک" },
    { firstname: "امیرخاتم", lastname: "پدرام", company: "امن پرداز آماتیس" },
    { firstname: "علی", lastname: "پرتوی", company: "اسنپ" },
    { firstname: "مهدی", lastname: "پندارش", company: "" },
    { firstname: "محسن", lastname: "پهلوان‌زاده", company: "سازمان فرهنگ" },
    { firstname: "پیمان", lastname: "پیمان نژاد", company: "" },
    { firstname: "مهرداد", lastname: "تاری", company: "میزبان داده پاسارگاد" },
    { firstname: "امیررضا", lastname: "ترویج", company: "کافه بازار" },
    { firstname: "مهدی", lastname: "تکلو", company: "سپهر سبزخاورمیانه" },
    { firstname: "خانم", lastname: "توانا", company: "" },
    { firstname: "محمداحسان", lastname: "توکلی", company: "زرین‌پال" },
    { firstname: "پویا", lastname: "تیموری", company: "دیجی پی" },
    { firstname: "امیرحسین", lastname: "ثابت", company: "صفرویک" },
    { firstname: "محمد امین", lastname: "جابرمرادی", company: "" },
    { firstname: "حسن", lastname: "جباری", company: "آسیاتک" },
    {
      firstname: "محسن",
      lastname: "جدیدی",
      company: "ارتباط گستران هوشمند وانا",
    },
    { firstname: "پری", lastname: "جعفرزاده", company: "سازمان صدا و سیما" },
    { firstname: "محمدحسن", lastname: "جعفرزاده", company: "" },
    { firstname: "رضا", lastname: "جعفری", company: "دماوند" },
    { firstname: "بهمن", lastname: "جعفری", company: "رایان هم افزا" },
    { firstname: "زهرا", lastname: "جعفری", company: "" },
    { firstname: "محمدحسین", lastname: "جعفری ملک", company: "علی بابا" },
    { firstname: "احسان", lastname: "جلال الدینی", company: "شرکت شاپرک" },
    {
      firstname: "بنیامین",
      lastname: "جمالی فرد",
      company: "میزبان داده پردیس",
    },
    { firstname: "پوریا", lastname: "جهانگیری فر", company: "پلی کو" },
    { firstname: "محمد رضا", lastname: "جوادی", company: "وب داده" },
    {
      firstname: "مرتضی",
      lastname: "چشمی",
      company: "پیشگامان توسعه ارتباطات",
    },
    {
      firstname: "محبوبه",
      lastname: "چنگیزی محمدی",
      company: "سازمان فناوری اطلاعات ایران",
    },
    { firstname: "فریماه", lastname: "چوبداری", company: "" },
    { firstname: "ف", lastname: "چیذری", company: "irost" },
    { firstname: "محمد", lastname: "چینی ساز", company: "چکاوک" },
    { firstname: "حسین", lastname: "حاتمی", company: "کافی نت نیوشا" },
    { firstname: "مهدی", lastname: "حبشی", company: "انتقال داده های آسیاتک" },
    { firstname: "افروز", lastname: "حبیبی", company: "آسیاتک" },
    { firstname: "عرفان", lastname: "حبیبی", company: "هم‌روش" },
    { firstname: "علیرضا", lastname: "حجت", company: "ایرانسل" },
    { firstname: "مهدی", lastname: "حجتی", company: "ایرانسل" },
    { firstname: "سجاد", lastname: "حسن زاده", company: "دوآپس یار" },
    { firstname: "رضا", lastname: "حسنی", company: "میزبان داده شتابان" },
    { firstname: "سیدمحمدرضا", lastname: "حسینی", company: "چکاوک" },
    { firstname: "سید حمید رضا", lastname: "حسینی", company: "کرانه" },
    { firstname: "محمد مهدی", lastname: "حسینی", company: "مگفا" },
    {
      firstname: "ابوالفضل",
      lastname: "حسینی",
      company: "نوین ارتباط تابان آپادانا",
    },
    { firstname: "سید محمد", lastname: "حسینی", company: "هم روش" },
    { firstname: "سیدحمیدرضا", lastname: "حسینی", company: "" },
    { firstname: "عرشیا", lastname: "خادمی", company: "میزبان داده پردیس" },
    { firstname: "نیما", lastname: "خان محمدی", company: "آروان کلاد" },
    { firstname: "مهدی", lastname: "خانلری", company: "افرانت" },
    { firstname: "زهرا", lastname: "خانی", company: "اسیاتک" },
    { firstname: "وحید", lastname: "خسروجردی", company: "نوین پردازان" },
    {
      firstname: "سعید",
      lastname: "خسروی",
      company: "تدبیرپردازان ایده‌های ابری",
    },
    { firstname: "سید مهران", lastname: "خلدی", company: "همروش" },
    { firstname: "سید مهدی", lastname: "خلفه لو", company: "هم‌روش" },
    { firstname: "مسعود", lastname: "خلیل نژاد", company: "" },
    { firstname: "سیدعلی", lastname: "خلیلی", company: "داده پرداز فنانو" },
    { firstname: "محسن", lastname: "خوانساری", company: "" },
    { firstname: "مصطفی", lastname: "خوشنود", company: "امن افزار هوپاد" },
    { firstname: "وحید", lastname: "خوشنود", company: "تک نت" },
    { firstname: "امیر", lastname: "خیاط احسانی", company: "ابردراک" },
    { firstname: "کیان", lastname: "دادور", company: "آیویوید" },
    { firstname: "داویت", lastname: "داودیان", company: "فناوران شبکه سینداد" },
    { firstname: "علی", lastname: "داوری", company: "تولید نیروی برق شاهرود" },
    { firstname: "علیرضا", lastname: "داوودی", company: "نکست بیت" },
    { firstname: "اسحاق", lastname: "دباغ", company: "سپهرنت" },
    {
      firstname: "علی محمد",
      lastname: "دربندی",
      company: "پیشگامان شبکه راتا و پروازسیستم",
    },
    { firstname: "محمدرضا", lastname: "درجزینی", company: "مدیاپردازسیستم" },
    { firstname: "حسین", lastname: "درواری", company: "" },
    { firstname: "امیرحسین", lastname: "درویش", company: "" },
    { firstname: "زهرا", lastname: "دل افروز", company: "رایانه خدمات امید" },
    {
      firstname: "علی",
      lastname: "دلشاد نداف",
      company: "پژوهشگاه علوم انسانی و مطالعات فرهنگی",
    },
    { firstname: "امین", lastname: "ده باشی", company: "افرانت" },
    { firstname: "مهدی", lastname: "دهستانی", company: "" },
    { firstname: "مهدی", lastname: "دهقانی", company: "" },
    { firstname: "حسین", lastname: "ذاکر", company: "انتقال داده ماهان" },
    { firstname: "میثم", lastname: "ذوقی", company: "KPP" },
    { firstname: "محمد", lastname: "راد", company: "همروش" },
    { firstname: "سینا", lastname: "رادمهر", company: "همروش" },
    { firstname: "آرش", lastname: "راست پور", company: "ارتباط افزار زمرد" },
    { firstname: "علی", lastname: "راسخی نژاد", company: "مبین‌هاست" },
    { firstname: "پویان", lastname: "رحمانی", company: "شیمی دارویی داروپخش" },
    {
      firstname: "علی",
      lastname: "رحمانی",
      company: "داده نگاران نرم افزار پارسی",
    },
    {
      firstname: "سعید",
      lastname: "رحمت",
      company: "ارتباطات نت میهن (میهن وب هاست)",
    },
    { firstname: "حدیث", lastname: "رحمتی", company: "" },
    {
      firstname: "امیرحسین",
      lastname: "رحمتیان ماسوله",
      company: "بانک خاورمیانه",
    },
    {
      firstname: "احسان",
      lastname: "رحمتیان ماسوله",
      company: "راهکار داده پرداز کهن",
    },
    { firstname: "عبدالعظیم", lastname: "رحیم‌ پور", company: "" },
    { firstname: "احمد", lastname: "رزاقی", company: "داده ورزی سداد" },
    { firstname: "علی اکبر", lastname: "رستگار", company: "لایزر" },
    { firstname: "سینا", lastname: "رستمی", company: "" },
    { firstname: "علی", lastname: "رشیدی", company: "پارس آنلاین" },
    { firstname: "رضا", lastname: "رضا صلاحی", company: "Eefaceram" },
    { firstname: "بهاره", lastname: "رضازاده", company: "شاتل" },
    { firstname: "علی", lastname: "رضاعلی", company: "فلایتیو" },
    { firstname: "علی", lastname: "رضایی", company: "Zagros.Host" },
    { firstname: "شایان", lastname: "رضایی", company: "آروان کلاد" },
    { firstname: "بهشاد", lastname: "رضایی", company: "تک نت" },
    { firstname: "سید رسول", lastname: "رضوی", company: "" },
    { firstname: "حسین", lastname: "رفائی", company: "ایرانسل" },
    {
      firstname: "مسعود",
      lastname: "رمضانی",
      company: "حسابگر پرداز غرب (تک نت)",
    },
    { firstname: "آزاد", lastname: "روانشید", company: "ناک" },
    { firstname: "امیر عباس", lastname: "زارع", company: "همراه اول" },
    {
      firstname: "امیرحسین",
      lastname: "زارعیان",
      company: "ایکاد فناوری آرکان",
    },
    { firstname: "حسین", lastname: "زاهدی", company: "آریاسرور" },
    { firstname: "علیرضا", lastname: "زاهدی", company: "آریاسرور" },
    { firstname: "علی", lastname: "زاهدی", company: "دیده بان نت" },
    {
      firstname: "خدیجه",
      lastname: "زاهدی آرانی",
      company: "شرکت مخابرات ایران",
    },
    {
      firstname: "مهدیه",
      lastname: "زاهدی دیزجی",
      company: "شرکت مخابرات ایران",
    },
    { firstname: "محمد", lastname: "زبردست", company: "" },
    {
      firstname: "مجتبی",
      lastname: "زمانزاده",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "سروش", lastname: "زندی", company: "فناوری ارتباطات پویان" },
    { firstname: "میلاد", lastname: "زنگی", company: "میزبان داده شتابان" },
    { firstname: "محمد مهدی", lastname: "زینالی", company: "هم‌روش" },
    { firstname: "احسان", lastname: "زینلیان زاده", company: "ایفاسرام" },
    { firstname: "سارمن", lastname: "سارویان", company: "" },
    { firstname: "ستاره", lastname: "سپهر", company: "ایرانسل" },
    { firstname: "فرید", lastname: "ستاری", company: "هم‌روش" },
    { firstname: "سونیتا", lastname: "سراب‌پور", company: "روزنامه شرق" },
    { firstname: "سید سروش", lastname: "سلطانی", company: "ابردراک" },
    { firstname: "سید سینا", lastname: "سلطانی", company: "ابردراک" },
    { firstname: "رائین", lastname: "سلطانی", company: "اسنپ! باکس" },
    {
      firstname: "مسعود",
      lastname: "سلطانی",
      company: "شرکت دیده بان نت/servco",
    },
    { firstname: "محمد", lastname: "سلیمی", company: "آسیاتک" },
    { firstname: "مهدی", lastname: "سواری", company: "مبنا گسترش سیستم آروین" },
    { firstname: "شروین", lastname: "سوری", company: "چکاوک" },
    { firstname: "محمود", lastname: "سیدرضویان", company: "POL" },
    { firstname: "سیداحسان", lastname: "سیدعلی اکبر", company: "اسنپ" },
    { firstname: "محمدرضا", lastname: "سیفی", company: "هم‌روش" },
    { firstname: "امیرمسعود", lastname: "شاکر", company: "فلایتیو" },
    { firstname: "سید احمد", lastname: "شاه نعمت اله یزدی", company: "" },
    { firstname: "میلاد", lastname: "شاهی", company: "سیمرغ" },
    { firstname: "عادل", lastname: "شاهینی", company: "N/A" },
    { firstname: "علی", lastname: "شرکت", company: "شرکت" },
    { firstname: "عبدالله", lastname: "شریعتی", company: "میزبان داده پردیس" },
    { firstname: "محمد رضا", lastname: "شریعتی", company: "" },
    { firstname: "محمد حسام", lastname: "شریف", company: "" },
    { firstname: "امیررضا", lastname: "شریفی", company: "پرهام سیستم" },
    { firstname: "مهرنوش", lastname: "شعبانی", company: "" },
    { firstname: "فرشاد", lastname: "شکری سرشکه", company: "" },
    { firstname: "مهدی", lastname: "شلاهی", company: "کافه آموزش" },
    { firstname: "رسول", lastname: "شماعی", company: "شرکت صبا هاست" },
    {
      firstname: "میثم",
      lastname: "شمرآبی",
      company: "زیرساخت امن خدمات تراکنشی بانک ملت",
    },
    { firstname: "محمدعرفان", lastname: "شمس", company: "اروان کلاد" },
    { firstname: "مهدی", lastname: "شهابی", company: "نگین گهر خاورمیانه" },
    { firstname: "امیر", lastname: "شهریاری", company: "پرداخت اول کیش" },
    { firstname: "داود", lastname: "شهریاری", company: "" },
    { firstname: "وحید", lastname: "شهسواری", company: "پیشگام رایان" },
    { firstname: "سهیل", lastname: "شهسواری", company: "نگین گهر خاورمیانه" },
    { firstname: "محمدجواد", lastname: "شیخ زاده", company: "هلدینگ گلستان" },
    { firstname: "حامد", lastname: "شیروانی", company: "" },
    { firstname: "سعید", lastname: "صابری", company: "Ressis" },
    { firstname: "محمد", lastname: "صاحبدل", company: "همراه اول" },
    { firstname: "مهران", lastname: "صاحبدل", company: "" },
    { firstname: "سید علی", lastname: "صالح ایمن", company: "نگاه روشن پارس" },
    { firstname: "محمد", lastname: "صائب", company: "" },
    { firstname: "امیر", lastname: "صرامی", company: "" },
    { firstname: "سجاد", lastname: "صفایی", company: "سیتاد" },
    { firstname: "حمیدرضا", lastname: "صفرپور", company: "" },
    { firstname: "حمید", lastname: "صفری", company: "ستون" },
    { firstname: "امیر", lastname: "صفری فروشانی", company: "دورانتاش" },
    { firstname: "فواد", lastname: "صمدنژاد", company: "هواوی" },
    { firstname: "فاطمه", lastname: "صمدی پور", company: "میزبان گستر پرداز" },
    {
      firstname: "پیام",
      lastname: "صمدیان",
      company: "شرکت فناوران اطلاعات ابرباران",
    },
    { firstname: "محمد", lastname: "ضربعلی زاده", company: "ابرآروان" },
    { firstname: "بهار", lastname: "ضمیری", company: "" },
    { firstname: "ایلیا", lastname: "طالبی", company: "چکاوک" },
    { firstname: "رضا", lastname: "طالبی", company: "رسیس" },
    { firstname: "محسن", lastname: "طهماسبی", company: "" },
    {
      firstname: "امیر طاها",
      lastname: "طهماسبی ابدر",
      company: "پردازش هوشمند البرز",
    },
    { firstname: "محمدرضا", lastname: "ظریف سلطانی", company: "مشهدهاست" },
    {
      firstname: "علی",
      lastname: "عابدی",
      company: "فناوران اطلاعات ابر باران",
    },
    { firstname: "عابس", lastname: "عابسی", company: "ارمان داده پرداز اترا" },
    { firstname: "مهدی", lastname: "عادلی", company: "مبنا تلکام" },
    { firstname: "دانیال", lastname: "عباس زاده", company: "virak" },
    { firstname: "فاطمه", lastname: "عباسی", company: "چکاوک" },
    { firstname: "وحید", lastname: "عباسی", company: "" },
    { firstname: "محمد حسین", lastname: "عبائیانی", company: "ابر آروان" },
    { firstname: "فرشاد", lastname: "عبدلی محمودی", company: "" },
    { firstname: "محمد", lastname: "عبدی", company: "چابکان" },
    { firstname: "ابوالفضل", lastname: "عربی", company: "ایاس تی وی" },
    { firstname: "میترا", lastname: "علی اکبری", company: "خسرونیکوپلاست" },
    { firstname: "حسین", lastname: "علی تبار", company: "ایرانسل" },
    {
      firstname: "علیرضا",
      lastname: "علیمردانی",
      company: "میزبان داده شتابان",
    },
    { firstname: "مجید", lastname: "عیسی لو", company: "میزبان داده پاسارگاد" },
    { firstname: "زهرا", lastname: "غریب زاده", company: "لیموهاست" },
    { firstname: "امیرحسین", lastname: "غفاری", company: "گپ فیلم" },
    { firstname: "بهروز", lastname: "غفوریان", company: "بهسا" },
    { firstname: "امیر", lastname: "غلامی", company: "DOMIL" },
    {
      firstname: "محمد رضا",
      lastname: "غلامی",
      company: "ارتباطات ثابت پارسیان",
    },
    { firstname: "طاها", lastname: "فراهانی", company: "" },
    {
      firstname: "فرهاد",
      lastname: "فرجادمنش",
      company: "داده پردازی رایاسپهر",
    },
    { firstname: "مهدی", lastname: "فرجی", company: "پیشگامان توسعه ارتباطات" },
    { firstname: "مجتبی", lastname: "فرخی فر", company: "میزبان گستر پرداز" },
    { firstname: "مهرداد", lastname: "فرزام فر", company: "آریا سرور" },
    { firstname: "امیرحسین", lastname: "فروزانی", company: "ابردراک" },
    { firstname: "محمدرضا", lastname: "فلاحی", company: "" },
    { firstname: "علی", lastname: "فهمیده", company: "همروش" },
    {
      firstname: "امیر",
      lastname: "فولادوند",
      company: "داده رایانش ابری پردیس",
    },
    { firstname: "حسن", lastname: "فولادی", company: "زفتا" },
    { firstname: "فاطمه", lastname: "قاسمی", company: "اسیاتک" },
    { firstname: "المیرا", lastname: "قاسمی", company: "افرانت" },
    { firstname: "امیرحسین", lastname: "قاسمی", company: "" },
    { firstname: "سیداحسان", lastname: "قاسمیان", company: "" },
    { firstname: "احسان", lastname: "قاضی‌زاده", company: "ستون" },
    { firstname: "حامد", lastname: "قربان زاده", company: "مهرگان نت" },
    { firstname: "علیرضا", lastname: "قربتی", company: "مهیمن" },
    { firstname: "عرفان", lastname: "قوامی نیا", company: "سفرهای علی بابا" },
    { firstname: "امیرحسین", lastname: "کاشانی", company: "" },
    { firstname: "شاهین", lastname: "کاظمی", company: "آتیه داده پرداز" },
    { firstname: "محمد", lastname: "کاظمی", company: "گسترش ارتباطات مبنا" },
    { firstname: "عمید", lastname: "کاظمی", company: "" },
    { firstname: "ایمان", lastname: "کاظمی طلاچی", company: "Domil" },
    { firstname: "امیرحسین", lastname: "کامرانی", company: "ویرا شبکه آران" },
    { firstname: "سروش", lastname: "کاویانی", company: "لیموهاست" },
    { firstname: "کامران", lastname: "کبیری", company: "" },
    { firstname: "امیر", lastname: "کربلایی", company: "مدیا پرداز سیستم" },
    { firstname: "علی", lastname: "کرمی", company: "هم‌روش" },
    { firstname: "محمد امین", lastname: "کریمان", company: "راورو" },
    { firstname: "علیرضا", lastname: "کریمی", company: "NetworkDream" },
    { firstname: "زهرا", lastname: "کریمی", company: "" },
    { firstname: "فاطمه", lastname: "کریمیان", company: "گسترش ارتباطات صبا" },
    { firstname: "محمد", lastname: "کفاشی", company: "میزبان داده پردیس" },
    { firstname: "محمد", lastname: "کفایتی", company: "اسنپ" },
    { firstname: "حبیب", lastname: "کمایی", company: "Cafenetwork" },
    { firstname: "علیرضا", lastname: "کولیوند", company: "شاپرک" },
    { firstname: "مجید", lastname: "کی نژاد", company: "اسنپ" },
    { firstname: "محمدرضا", lastname: "کیانی", company: "دکتردکتر" },
    { firstname: "اشکان", lastname: "کیانی", company: "ستون" },
    { firstname: "نیلوفر", lastname: "کیایی", company: "" },
    {
      firstname: "پوریا",
      lastname: "گودرزی",
      company: "ستون(رایانش ابری هزاردستان)",
    },
    { firstname: "مبینا", lastname: "گودرزی", company: "" },
    { firstname: "احسان", lastname: "گورابی", company: "گسترش ارتباطات تالیا" },
    { firstname: "پیمان", lastname: "لاری", company: "خانه لینوکس شیراز" },
    { firstname: "محمد", lastname: "لیاقی", company: "" },
    { firstname: "ابراهیم", lastname: "مامانی", company: "هلدینگ زر" },
    { firstname: "علی", lastname: "مبشری", company: "هاست ایران" },
    { firstname: "شادی", lastname: "متعالی", company: "" },
    { firstname: "امیرحسین", lastname: "متینی", company: "آنلاین سرور" },
    { firstname: "ابراهیم", lastname: "مجتبایی", company: "پرداخت نوین" },
    { firstname: "رضا", lastname: "محبوبی", company: "ارتباطات ثابت پارسیان" },
    { firstname: "محمدحسین", lastname: "محسنی", company: "" },
    { firstname: "یاشار", lastname: "محمدی", company: "اطلاعات فناوران توکان" },
    { firstname: "محسن", lastname: "محمدی", company: "ایرانیکاسرور" },
    { firstname: "میلاد", lastname: "محمدی", company: "فرابورس ایران" },
    { firstname: "علیرضا", lastname: "محمدی", company: "فلایتیو" },
    { firstname: "علی", lastname: "محمدی", company: "نقش روز / پیشگامان" },
    { firstname: "فرزاد", lastname: "محمدی ستوده", company: "ایرانسل" },
    {
      firstname: "ارشاد",
      lastname: "مختاری افراکتی",
      company: "شرکت فناوری رایانه هوشمند",
    },
    { firstname: "حمید", lastname: "مداحیان", company: "Charisma" },
    {
      firstname: "زهیر",
      lastname: "محسن مرادی",
      company: "سازمان ثبت اسناد و املاک کشور",
    },
    { firstname: "علی", lastname: "مرادی", company: "میزبان داده شتابان" },
    { firstname: "مریم", lastname: "مروتی", company: "هوپاد" },
    { firstname: "حانیه", lastname: "مروی", company: "هم‌روش" },
    { firstname: "حسن", lastname: "مستحسن", company: "نگاه روشن پارس" },
    { firstname: "مریم", lastname: "مسعودی", company: "سازمان فناوری اطلاعات" },
    { firstname: "صابر", lastname: "مسگری", company: "ابرآروان" },
    { firstname: "مجید", lastname: "مسلمی", company: "چکاوک" },
    { firstname: "سینا", lastname: "مشیری گیلانی", company: "" },
    { firstname: "جلال", lastname: "مظاهری", company: "" },
    { firstname: "محمد", lastname: "مظفری", company: "" },
    { firstname: "علیرضا", lastname: "معتمدیان", company: "بانک ایران زمین" },
    { firstname: "رضا", lastname: "معصوم وند", company: "" },
    {
      firstname: "مهرداد",
      lastname: "مقاره عابد",
      company: "نت افراز ایرانیان",
    },
    { firstname: "فریبرز", lastname: "مقامی", company: "نقش اول کیفیت" },
    { firstname: "مهرزاد", lastname: "مقدس", company: "" },
    { firstname: "مریم", lastname: "مقدس برهان", company: "همروش" },
    {
      firstname: "مجید",
      lastname: "مقصودفر",
      company: "دانشگاه علوم پزشکی تبریز",
    },
    { firstname: "مهدی", lastname: "مقصودی", company: "دیده بان نت" },
    { firstname: "مسعود", lastname: "مقصودی", company: "" },
    { firstname: "آرش", lastname: "مقیمیان", company: "همراه اول" },
    { firstname: "سیدامیرعلی", lastname: "ملک", company: "ایرانسل" },
    { firstname: "نیما", lastname: "ملک زاده", company: "رسپینا" },
    { firstname: "امین", lastname: "ملک قاسمی", company: "" },
    { firstname: "فرشاد", lastname: "منتخبی", company: "Zafta" },
    { firstname: "داود", lastname: "منتظری", company: "مبین هاست" },
    { firstname: "مجتبی", lastname: "منیعی", company: "تک نت" },
    { firstname: "دلارام", lastname: "مهدوی", company: "تاژان سیستم" },
    { firstname: "روح‌اله", lastname: "مهدی‌لو", company: "...." },
    { firstname: "شایان", lastname: "موسوی", company: "خبره پرداز پارس" },
    { firstname: "سیده سارا", lastname: "موسوی راد", company: "ابردراک" },
    { firstname: "سید علی", lastname: "موسوی زاده", company: "ایفاسرام" },
    {
      firstname: "مهرداد",
      lastname: "موسوی نجف آبادی",
      company: "سازمان فاوا  شهرداری اصفهان",
    },
    { firstname: "احسان", lastname: "مومنی", company: "داده ورزی سداد" },
    { firstname: "سید علیرضا", lastname: "میراحمدی", company: "" },
    { firstname: "ایمان", lastname: "میرآخورلی", company: "لایوکده" },
    { firstname: "ارشاد", lastname: "میردامادی", company: "" },
    { firstname: "حسین", lastname: "میرزایی", company: "" },
    { firstname: "محمد", lastname: "میناوند", company: "گیلاس کامپیوتر" },
    { firstname: "امین", lastname: "نادری", company: "نوین کلود" },
    {
      firstname: "محمدنوید",
      lastname: "نجاتی",
      company: "دانشگاه پیام نور سازمان مرکزی",
    },
    { firstname: "صادق", lastname: "نجاتی زاده", company: "" },
    {
      firstname: "مژگان",
      lastname: "نجف پور",
      company: "مرکز وکلا قوه قضائیه",
    },
    { firstname: "ابوالفضل", lastname: "نجفی", company: "ایرانسل" },
    { firstname: "نوید", lastname: "نجفی", company: "" },
    { firstname: "هادی", lastname: "نجفی", company: "" },
    {
      firstname: "اشکان",
      lastname: "نصیری",
      company: "ایران هاست و هاست ایران",
    },
    { firstname: "آیسان", lastname: "نظرمحمدی", company: "خبرگزاری ایسنا" },
    { firstname: "امیرحسین", lastname: "نظری", company: "چکاوک پردازش هوشمند" },
    { firstname: "سارا", lastname: "نظری", company: "" },
    { firstname: "ماهرخ", lastname: "نعمت اللهی", company: "ایرانسل" },
    { firstname: "حمید", lastname: "نعیم آبادی", company: "DOMIL" },
    { firstname: "یوسف", lastname: "نعیمی", company: "" },
    { firstname: "محمد رضا", lastname: "نفیسی", company: "بیمه آسیا" },
    { firstname: "حسین", lastname: "نکومنش", company: "اسنپ" },
    { firstname: "لیلا", lastname: "نکویی", company: "" },
    { firstname: "کوروش", lastname: "نوروزی", company: "" },
    { firstname: "علیرضا", lastname: "نوروزی صفا", company: "لایزر" },
    { firstname: "مهدی", lastname: "نوزادی", company: "فرا ارتباط گستر پویا" },
    { firstname: "علی", lastname: "نیکنام", company: "پردیس" },
    { firstname: "سیدمحمد", lastname: "هاشمی", company: "ایرانیکاسرور" },
    { firstname: "مهدی", lastname: "هاشمی نسب", company: "داده پردازی فن آوا" },
    { firstname: "مجید", lastname: "هداوندسیری", company: "وانا" },
    { firstname: "کسری", lastname: "هدایت", company: "Domil" },
    {
      firstname: "بهنود",
      lastname: "هلیلیان",
      company: "پردازش اطلاعات مالی کاریزما",
    },
    {
      firstname: "کامبیز",
      lastname: "همایونی",
      company: "پیشگامان توسعه ارتباطات",
    },
    { firstname: "علی اکبر", lastname: "همتی", company: "" },
    { firstname: "رضا", lastname: "واحدی", company: "پیشگامان توسعه ارتباطات" },
    { firstname: "حسین", lastname: "واحدی", company: "چکاووک" },
    { firstname: "مهدی", lastname: "وارسته", company: "امنش" },
    { firstname: "وحید", lastname: "واشقانی", company: "" },
    { firstname: "افشین", lastname: "واعظی", company: "آروان کلاد" },
    {
      firstname: "محسن",
      lastname: "وحدت",
      company: "ایده گزین ارتباطات روماک (اسنپ)",
    },
    { firstname: "امیررضا", lastname: "ولی زاده", company: "" },
    { firstname: "سید شهروز", lastname: "ویژه", company: "لایزر" },
    { firstname: "محمد", lastname: "يادگاري", company: "ارتبانت" },
    { firstname: "مهدی", lastname: "یاسینی", company: "" },
    { firstname: "محمد", lastname: "یعقوبی", company: "ایرانسل" },
    { firstname: "حسام", lastname: "یوسفی", company: "NextBit" },
    { firstname: "حسین", lastname: "یوسفی", company: "" },
    { firstname: "زهرا", lastname: "عزیزی", company: "" },
    { firstname: "محمد امین", lastname: "میانرودی", company: "" },
    { firstname: "آذین", lastname: "چشفر", company: "" },
    { firstname: "عرفان", lastname: "مخبریان", company: "" },
    { firstname: "صدرا", lastname: "وزیری", company: "" },
    { firstname: "علی", lastname: "فلاح", company: "" },
    { firstname: "امیر", lastname: "کمندلو", company: "" },
    { firstname: "محمدحسین", lastname: "پورنوری", company: "" },
    { firstname: "محمدمهدی", lastname: "مجیدی", company: "" },
    { firstname: "علی", lastname: "میرابیان", company: "" },
    { firstname: "داود", lastname: "منتظری", company: "مبین‌هاست" },
    { firstname: "سعیده", lastname: "محمودیان", company: "برق منطقه ای سمنان" },
    { firstname: "محمدرضا", lastname: "شریفی", company: "آروان کلاد" },
    { firstname: "احسان", lastname: "علی‌زاده", company: "آروان کلاد" },
    { firstname: "محمود", lastname: "احمدی", company: "آروان کلاد" },
    { firstname: "توحید", lastname: "نصیرزاده", company: "آروان کلاد" },
    { firstname: "محمدرضا", lastname: "داورزنی", company: "آروان کلاد" },
    { firstname: "محسن", lastname: "سالک", company: "آروان کلاد" },
    { firstname: "علی", lastname: "فرهادیان", company: "آروان کلاد" },
    { firstname: "هستی", lastname: "شهریزفر", company: "آروان کلاد" },
    { firstname: "پویا", lastname: "پیرحسینلو", company: "آروان کلاد" },
    { firstname: "فاطمه", lastname: "مظاهریان", company: "" },
    { firstname: "محمدجواد", lastname: "عرشیان", company: "خبرگزاری ایسنا" },
    { firstname: "امیرحسین", lastname: "معارف", company: "خلیج سرور" },
    { firstname: "محمدصادق", lastname: "شریفی", company: "خلیج سرور" },
    { firstname: "حسین", lastname: "زابل زاده", company: "XaaS" },
    { firstname: "رضا", lastname: "خالواکبری", company: "ایرانسل" },
    { firstname: "احسان", lastname: "حسینی", company: "اسپارا" },
    { firstname: "آرش", lastname: "حاتمی", company: "آروان کلاد" },
  ],
};
